### ISSUE TITLE
Emit callback lets client crash the server

### ISSUE THREAD

**Issue by henvic** [socketio/socket.io#1102]
I've something like the following code on the server:

``` javascript
//...
io.sockets.on('connection', function (socket) {
    //...
    socket.on("/nick", function (nick, callbackfn) {
        //...
        var data = user.getByNick(nick);
        callbackfn(data);
    });
});
```

And on the client I've this:

``` javascript
//...
socket.emit("/nick", nick,
    function (response) {
        if (! response.error) {
            //...
        } else {
            user.set(response);
        }
    }
);
```

And everything works smoothly.

But if I change my client-side code to:

``` javascript
//...
socket.emit("/nick", nick);
```

This happens:

```
/Users/henvic/projects/mgr/cahier/application/node/server.js:156
                callbackfn(response);
                ^
TypeError: undefined is not a function
    at Socket.<anonymous> (/foo/application/node/server.js:156:17)
    at Socket.EventEmitter.emit [as $emit] (events.js:93:17)
    at SocketNamespace.handlePacket (/foo/application/node/node_modules/socket.io/lib/namespace.js:335:22)
    at Manager.onClientMessage (/foo/application/node/node_modules/socket.io/lib/manager.js:487:38)
    at WebSocket.Transport.onMessage (/foo/application/node/node_modules/socket.io/lib/transport.js:387:20)
    at Parser.<anonymous> (/foo/application/node/node_modules/socket.io/lib/transports/websocket/hybi-16.js:39:10)
    at Parser.EventEmitter.emit (events.js:93:17)
    at opcodeHandlers.1.finish (/foo/application/node/node_modules/socket.io/lib/transports/websocket/hybi-16.js:288:16)
    at Parser.opcodeHandlers.1.expectData [as expectHandler] (/foo/application/node/node_modules/socket.io/lib/transports/websocket/hybi-16.js:299:15)
    at Parser.add (/foo/application/node/node_modules/socket.io/lib/transports/websocket/hybi-16.js:466:24)
```

The fix for me: test if callbackfn is defined (i.e., typeof callbackfn !== "undefined").

Is this a bug, a hidden "feature" (which, if the case, should be documented) or what?

**Comment by chirag04** [comment]
@rauchg imo socket.io should default to an empty func internally and ensure that callback is always available in the public api. this is just our production server and was hard to discover given that callback is not documented. 

If you agree i can send a PR.

**Comment by darrachequesne** [comment]
@chirag04 may I ask what fix you do suggest?

**Comment by chirag04** [comment]
I suggest documenting the second arg of the event callback and make it the the public api. Behind the scene, send ack to client if second arg is called. Makes sense?

**Comment by darrachequesne** [comment]
@chirag04 I think the issue is that the number of arguments is not limited to 2. `socket.emit('myevent', arg1, arg2, arg3, arg4)` and `socket.emit('myevent', cb)` are perfectly valid for example.

**Comment by chirag04** [comment]
@darrachequesne interesting. If that's the case then can atleast document the args. Or they are already documented and i'm not able to find them?

**Comment by darrachequesne** [comment]
@chirag04 the documentation is there: https://github.com/socketio/socket.io/blob/master/docs/API.md#socketemiteventname-args-ack

Any improvement is welcome!
