### ISSUE TITLE
Cannot find 'ws' package

### ISSUE THREAD

**Issue by chriso** [socketio/socket.io#1112]
It looks like the `ws` dep was removed in 8daa71302da40d43e8b817d54b2c8f05848cdb98 even though it's still required by `lib/manager.js:23`

A fresh install gives the following error

``` bash
/tmp $ npm install -s socket.io

> ws@0.4.25 install /private/tmp/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/bufferutil.node
  SOLINK_MODULE(target) Release/bufferutil.node: Finished
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/validation.node
  SOLINK_MODULE(target) Release/validation.node: Finished
socket.io@0.9.13 node_modules/socket.io
├── base64id@0.1.0
├── policyfile@0.0.4
├── redis@0.7.3
└── socket.io-client@0.9.11 (xmlhttprequest@1.4.2, uglify-js@1.2.5, active-x-obfuscator@0.0.1, ws@0.4.25)
/tmp $ echo 'require("socket.io")' > test.js
/tmp $ node test.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:362:17)
    at require (module.js:378:17)
    at Object.<anonymous> (/private/tmp/node_modules/socket.io/lib/manager.js:23:23)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:362:17)
```

**Comment by carterh062** [comment]
This comment above helped me as well. 
Erase full node_modules folder
npm cache clean
npm install

**Comment by antoniobrandao** [comment]
I'm having this problem with socket.io-client 1.1.0 and I need to use this version.
