### ISSUE TITLE
Error using msgpack with redis (store)

### ISSUE THREAD

**Issue by ifraixedes** [socketio/socket.io#1135]
Hi, 

I set up the **RedisStore** in my current web application that use socket.io, and I realized that if I install **msgpack** and I don't set the options "pack" and "unpack" in the **RedisStore** instance, so **RedisStore** use **msgpack** by defaul, my application crashes when the first client is connected or I emit the first message using the "socket server" (emitting message to all the sockets connected under a namespace).

If I **uninstall msgpack**, so RedisStore use JSON.stringify to pack and JSON.parse to unpack, then the application works.

The error that I got is:
events.js:68
        throw arguments[1]; // Unhandled 'error' event
                       ^
TypeError: First argument must be a Buffer
    at RedisClient.message (/home/ifraixedes/workspace/projects/iWazat/workspace/impl/r20130000/server/node_modules/socket.io/lib/stores/redis.js:126:24)
    at RedisClient.EventEmitter.emit (events.js:123:20)
    at RedisClient.return_reply (/home/ifraixedes/workspace/projects/iWazat/workspace/impl/r20130000/server/node_modules/socket.io/node_modules/redis/index.js:601:22)
    at RedisReplyParser.RedisClient.init_parser (/home/ifraixedes/workspace/projects/iWazat/workspace/impl/r20130000/server/node_modules/socket.io/node_modules/redis/index.js:265:14)
    at RedisReplyParser.EventEmitter.emit (events.js:93:17)
    at RedisReplyParser.add_multi_bulk_reply (/home/ifraixedes/workspace/projects/iWazat/workspace/impl/r20130000/server/node_modules/socket.io/node_modules/redis/lib/parser/javascript.js:312:14)
    at RedisReplyParser.send_reply (/home/ifraixedes/workspace/projects/iWazat/workspace/impl/r20130000/server/node_modules/socket.io/node_modules/redis/lib/parser/javascript.js:273:18)
    at RedisReplyParser.execute (/home/ifraixedes/workspace/projects/iWazat/workspace/impl/r20130000/server/node_modules/socket.io/node_modules/redis/lib/parser/javascript.js:223:22)
    at RedisClient.on_data (/home/ifraixedes/workspace/projects/iWazat/workspace/impl/r20130000/server/node_modules/socket.io/node_modules/redis/index.js:478:27)
    at Socket.<anonymous> (/home/ifraixedes/workspace/projects/iWazat/workspace/impl/r20130000/server/node_modules/socket.io/node_modules/redis/index.js:79:14)
    at Socket.EventEmitter.emit (events.js:93:17)

**Comment by MaximeWillinger** [comment]
Same issue here. What was the solution?
