### ISSUE TITLE
Error: Max message was exceeded 

### ISSUE THREAD

**Issue by ajjain** [socketio/socket.io#1271]
I am using below code to add & shift data in an array. 

var socket  = new io.connect('/');
socket.on('message', function (msg) {
    console.log(msg);
        // line below add msg to series data and shift the top element
    random.addEvents(seriesData, msg);
    graph.update();
});

Below is the error encountered:
info: transport end (socket end)
debug: set close timeout for client XtvrVgNZjj9HXQPz0DNC
debug: cleared close timeout for client XtvrVgNZjj9HXQPz0DNC
debug: cleared heartbeat interval for client XtvrVgNZjj9HXQPz0DNC
debug: discarding transport
error: Error: Max message was exceeded (1052619). Possible causes: bad offset, corrupt log, message larger than max message size (1048576)
                      ^
Error: Max message was exceeded (1052619). Possible causes: bad offset, corrupt log, message larger than max message size (1048576)
    at Socket.<anonymous> (/home/nslabs/bam/web/node_modules/prozess/lib/Consumer.js:67:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:736:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:511:21)

**Comment by brainpoint** [comment]
how to fix this?
