### ISSUE TITLE
io.transports[socket.id] is undefined..!!

### ISSUE THREAD

**Issue by manpreetsingh2011** [socketio/socket.io#1397]
I had added this code on "connect" event of socket.io. It was working properly for a long time. 
But suddenly, I got the following error on my production code, as a result of which the server closed. I feel that this is a bug, because I should always get something in io.transports[socket.id]

/code/chat_app/Server.js:95
console.log( io.transports[socket.id].name );

TypeError: Cannot read property 'name' of undefined
at SocketNamespace.OnConnection (/code/var/www/html/live.myamcat.com/chat_app/Server.js:95:39)
at SocketNamespace.EventEmitter.emit [as $emit](events.js:117:20)
at connect (/usr/local/node_modules/socket.io/lib/namespace.js:292:10)
at /usr/local/node_modules/socket.io/lib/namespace.js:308:13
at SocketNamespace.authorize (/usr/local/node_modules/socket.io/lib/namespace.js:252:5)
at SocketNamespace.handlePacket (/usr/local/node_modules/socket.io/lib/namespace.js:302:14)
at Manager.handleClient (/usr/local/node_modules/socket.io/lib/manager.js:698:32)
at Manager.handleHTTPRequest (/usr/local/node_modules/socket.io/lib/manager.js:630:8)
at Manager.handleRequest (/usr/local/node_modules/socket.io/lib/manager.js:591:12)
at Server.<anonymous> (/usr/local/node_modules/socket.io/lib/manager.js:119:10)

**Comment by AlejandroHCruz** [comment]
Hi, I'm encountering a similar issue in which socket.id is undefined. Any guides or tips about what could be causing this to happen? Disclaimer: The server is working with bluebird.
