### ISSUE TITLE
unmask of undefined

### ISSUE THREAD

**Issue by BrunoWinck** [socketio/socket.io#1606]
A systematic failure I'm coming across on CentOS/NodeJS/Express/Socket.io 1.04
I don't see what I can do to work around that
Was working fine before 1.00, works fine on windows, stable across desktop browsers
 
/project/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:274
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                              ^
TypeError: Cannot call method 'unmask' of undefined
    at Receiver.unmask (
/project/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:274:47)
    at Receiver.opcodes.1.finish (
/project/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:389:25)
    at Receiver.expectHandler (
/project/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:378:33)
    at Receiver.add (
/project/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:93:24)
    at Socket.firstHandler (
/project/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:678:22)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:745:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:407:10)
    at emitReadable (_stream_readable.js:403:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)

**Comment by pjump** [comment]
I fixed it in https://github.com/einaros/ws . Socket.io depends on engine.io which depends on ws. If you get engine.io to use the lastest ws, it'll work.
