### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by i5ting** [socketio/socket.io#2004]
```
➜  socket.io git:(master) npm test

> socket.io@1.3.2 test /Users/sang/workspace/github/socket.io
> mocha --reporter dot --slow 200ms --bail


  ․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․․Note: warning expected and normal in test.
Missing error handler on `socket`.
Error: Illegal attachments
    at decodeString (/Users/sang/workspace/github/socket.io/node_modules/socket.io-parser/index.js:290:13)
    at Decoder.add (/Users/sang/workspace/github/socket.io/node_modules/socket.io-parser/index.js:238:14)
    at Client.ondata (/Users/sang/workspace/github/socket.io/lib/client.js:176:18)
    at Socket.emit (events.js:95:17)
    at Socket.onPacket (/Users/sang/workspace/github/socket.io/node_modules/engine.io/lib/socket.js:99:14)
    at WebSocket.emit (events.js:117:20)
    at WebSocket.Transport.onPacket (/Users/sang/workspace/github/socket.io/node_modules/engine.io/lib/transport.js:91:8)
    at WebSocket.Transport.onData (/Users/sang/workspace/github/socket.io/node_modules/engine.io/lib/transport.js:102:8)
    at WebSocket.onData (/Users/sang/workspace/github/socket.io/node_modules/engine.io/lib/transports/websocket.js:75:30)
    at WebSocket.emit (events.js:98:17)
    at Receiver.ontext (/Users/sang/workspace/github/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:798:10)
    at /Users/sang/workspace/github/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:473:18
    at /Users/sang/workspace/github/socket.io/node_modules/engine.io/node_modules/ws/lib/Receiver.js:357:7
    at /Users/sang/workspace/github/socket.io/node_modules/engine.io/node_modules/ws/lib/PerMessageDeflate.js:217:5
    at afterWrite (_stream_writable.js:277:3)
    at onwrite (_stream_writable.js:269:7)
    at WritableState.onwrite (_stream_writable.js:96:5)
    at afterTransform (_stream_transform.js:99:5)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at Zlib.callback (zlib.js:455:5)
․․․․․․․․․

  92 passing (13s)
  1 failing

  1) socket.io messaging many broadcasts binary data to rooms:
     Error: timeout of 2000ms exceeded
      at null.<anonymous> (/Users/sang/workspace/github/socket.io/node_modules/mocha/lib/runnable.js:175:14)
      at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)



npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0

```

**Comment by nkzawa** [comment]
Can you try the latest release version or master ? There is no problem on them for me.

**Comment by jbaumbach** [comment]
I'm getting the same error running $ npm test.  Just forked from the main repo an hour ago.

**Comment by amanpurohit** [comment]
Any update on this issue? I am using node 4.4.0 and getting the same issue after running `npm test`.
I have forked master branch.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
