### ISSUE TITLE
FileReader is not defined

### ISSUE THREAD

**Issue by codeniac** [socketio/socket.io#2028]
After a photo upload i try to send a message to specific socket like

```
io.to(socketID).emit("photo:uploaded", photoData);
```

but im getting the following error:

```
error: uncaughtException: FileReader is not defined date=Sun Mar 01 2015 23:50:44 GMT-0300 (BRT), pid=17191, uid=501, gid=20, cwd=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api, execPath=/opt/local/bin/node, version=v0.10.33, argv=[node, /Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/main.js], rss=84561920, heapTotal=67487232, heapUsed=38638984, loadavg=[2.6611328125, 2.15478515625, 2.06591796875], uptime=875868, trace=[column=28, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/binary.js, function=_removeBlobs, line=108, method=null, native=false, column=9, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/binary.js, function=_removeBlobs, line=126, method=null, native=false, column=9, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/binary.js, function=_removeBlobs, line=130, method=null, native=false, column=3, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/binary.js, function=Object.exports.removeBlobs, line=137, method=exports.removeBlobs, native=false, column=10, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/index.js, function=encodeAsBinary, line=207, method=null, native=false, column=5, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/index.js, function=Encoder.encode, line=131, method=encode, native=false, column=16, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-adapter/index.js, function=Adapter.broadcast, line=118, method=broadcast, native=false, column=18, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/lib/namespace.js, function=Namespace.emit, line=218, method=emit, native=false, column=29, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/src/socket.js, function=self.emitToUser, line=38, method=emitToUser, native=false, column=9, file=/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/src/socket.js, function=self.emitToUsers, line=50, method=emitToUsers, native=false], stack=[ReferenceError: FileReader is not defined,     at _removeBlobs (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/binary.js:108:28),     at _removeBlobs (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/binary.js:126:9),     at _removeBlobs (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/binary.js:130:9),     at Object.exports.removeBlobs (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/binary.js:137:3),     at encodeAsBinary (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/index.js:207:10),     at Encoder.encode (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-parser/index.js:131:5),     at Adapter.broadcast (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/node_modules/socket.io-adapter/index.js:118:16),     at Namespace.emit (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/node_modules/socket.io/lib/namespace.js:218:18),     at self.emitToUser (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/src/socket.js:38:29),     at self.emitToUsers (/Users/Me/Projetos/JOJO/Repos/JOJO.rest.api/src/socket.js:50:9)]
```

**Comment by nkzawa** [comment]
It looks the same issue with #2029.
What kind of data is `photoData`? Do you have `Blob` or `File` on the global scope?

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
