### ISSUE TITLE
EPIPE on new connection

### ISSUE THREAD

**Issue by timruffles** [socketio/socket.io#2105]
first connection fine, all others EPIPE.

iojs on both ends,  iojs 1.1.0, socket.io 1.3.5, socket.io-client 1.3.5, using `stackup` to track this down.

``` sh
Error: write EPIPE
    at Object.exports._errnoException (util.js:749:11)
    at exports._exceptionWithHostPort (util.js:772:20)
    at WriteWrap.afterWrite (net.js:744:14)
    ---- async ----
    at Adapter.add (/app/daemon/core/node_modules/socket.io/node_modules/socket.io-adapter/index.js:50:19)
    at Socket.join (/app/daemon/core/node_modules/socket.io/lib/socket.js:221:16)
    at Socket.onconnect (/app/daemon/core/node_modules/socket.io/lib/socket.js:274:8)
    at /app/daemon/core/node_modules/socket.io/lib/namespace.js:167:16
    at process._tickCallback (node.js:341:15)
    ---- async ----
    at /app/daemon/core/node_modules/socket.io/lib/namespace.js:156:13
    at Namespace.run (/app/daemon/core/node_modules/socket.io/lib/namespace.js:111:27)
    at Namespace.add (/app/daemon/core/node_modules/socket.io/lib/namespace.js:155:8)
    at Client.connect (/app/daemon/core/node_modules/socket.io/lib/client.js:74:20)
    at Server.onconnection (/app/daemon/core/node_modules/socket.io/lib/index.js:315:10)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:166:7)
    at Server.handshake (/app/daemon/core/node_modules/socket.io/node_modules/engine.io/lib/server.js:262:8)
    at /app/daemon/core/node_modules/socket.io/node_modules/engine.io/lib/server.js:184:12
    at Server.checkRequest (/app/daemon/core/node_modules/socket.io/lib/index.js:68:51)
    at Server.verify (/app/daemon/core/node_modules/socket.io/node_modules/engine.io/lib/server.js:127:17)
    at Server.handleRequest (/app/daemon/core/node_modules/socket.io/node_modules/engine.io/lib/server.js:174:8)
    at Server.<anonymous> (/app/daemon/core/node_modules/socket.io/node_modules/engine.io/lib/server.js:366:12)
    at Server.<anonymous> (/app/daemon/core/node_modules/socket.io/lib/index.js:258:16)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:169:7)
    at HTTPParser.parserOnIncoming (_http_server.js:471:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
    at Socket.socketOnData (_http_server.js:322:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:145:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at TCP.onread (net.js:508:20)
    ---- async ----
    at emitOne (events.js:82:20)
    at Server.emit (events.js:166:7)
    at TCP.onconnection (net.js:1362:8)
    ---- async ----
    at listen (net.js:1208:10)
    at Server.listen (net.js:1298:5)
    at Server.listen.Server.attach (/app/daemon/core/node_modules/socket.io/lib/index.js:214:9)
    at new Server (/app/daemon/core/node_modules/socket.io/lib/index.js:51:17)
    at Server (/app/daemon/core/node_modules/socket.io/lib/index.js:39:41)
```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
