### ISSUE TITLE
Socket 0.9.x install error

### ISSUE THREAD

**Issue by msemple1111** [socketio/socket.io#2133]
I have been trying to install socket.io version 0.9 all afternoon to no avail. 
When I Try 
```
sudo npm -g install socket.io@0.9.x
```
All I get back is
```
> ws@0.4.32 install /usr/local/lib/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/local/lib/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/usr/local/lib/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
socket.io@0.9.17 /usr/local/lib/node_modules/socket.io
├── base64id@0.1.0
├── policyfile@0.0.4
├── redis@0.7.3
└── socket.io-client@0.9.16 (xmlhttprequest@1.4.2, uglify-js@1.2.5, active-x-obfuscator@0.0.1, ws@0.4.32)
```
I am using raspberry pi B v1 with raspbian Debian. 
I have instaled node-gyp and reinstalled npm.
in /var/log/nodejs-socket-io.log
```
Error: Cannot find module 'socket.io'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/share/nginx/html/cakephp-2.5.4/rd_cake/Setup/Node.js/Logfile.node.js:5:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
error: Forever detected script exited with code: 1
error: Script restart attempt #19
```
in my /etc/init.d/nodejs-socket-io file
```
#!/bin/bash
### BEGIN INIT INFO
# Provides:             my-application
# Required-Start:       $syslog $remote_fs
# Required-Stop:        $syslog $remote_fs
# Should-Start:         $local_fs
# Should-Stop:          $local_fs
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    My Application
# Description:          My Application
### END INIT INFO

NAME="Node.js SocketIO"
NODE_BIN_DIR="/usr/bin"
NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
#APPLICATION_DIRECTORY="/usr/share/nginx/www/cake2/rd_cake/Setup/Node.js"
APPLICATION_DIRECTORY="/usr/share/nginx/html/cake2/rd_cake/Setup/Node.js"
APPLICATION_START="Logfile.node.js"
PIDFILE="/var/run/nodejs-socket-io.pid"
LOGFILE="/var/log/nodejs-socket-io.log"
 
PATH=$NODE_BIN_DIR:$PATH
export NODE_PATH=$NODE_PATH
 
start() {
    echo "Starting $NAME"
    forever --pidFile $PIDFILE --sourceDir $APPLICATION_DIRECTORY \
        -a -l $LOGFILE --minUptime 5000 --spinSleepTime 2000 \
        start $APPLICATION_START &
    RETVAL=$?
}
 
stop() {
    if [ -f $PIDFILE ]; then
        echo "Shutting down $NAME"
        forever stop $APPLICATION_START
        rm -f $PIDFILE
        RETVAL=$?
    else
        echo "$NAME is not running."
        RETVAL=0
    fi
}
 
restart() {
    echo "Restarting $NAME"
    stop
    start
}
 
status() {
    echo "Status for $NAME:"
    forever list
    RETVAL=$?
}
 
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $RETVAL
```

**Comment by nkzawa** [comment]
Can't you use the latest version? It's difficult to support old versions.

**Comment by msemple1111** [comment]
I have tried using 1.3.5 also but the script I have used was written for 0.9.
1.3.5 has the same issue with the same output

**Comment by nkzawa** [comment]
Umm, maybe it's the same issue with https://github.com/Automattic/socket.io/issues/2132 ?

**Comment by msemple1111** [comment]
Tried that but even more errors:
```bash
sudo npm install automattic/socket.io
```
 ```bash
> utf-8-validate@1.1.0 install /home/pi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/.node-gyp"
make: Entering directory '/home/pi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory '/home/pi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build'

> bufferutil@1.1.0 install /home/pi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/.node-gyp"
make: Entering directory '/home/pi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
make: Leaving directory '/home/pi/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil/build'

> utf-8-validate@1.0.1 install /home/pi/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.1"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/pi/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/.node-gyp"
```
Then it hangs and all network processes stop.

**Comment by azorac** [comment]
@msemple1111 if you ended up here by following RadiusDesk installation guide, you've probably not installed the dependencies in the local directory (like I foolishly overlooked myself) as the guide doesn't mention it. Things like require('package') etc require the package to be present in the working directory and not globally.
So basically:
```
# 1. install socket.io, and mysql locally
cd /usr/share/nginx/html/cake2/rd_cake/Setup/Node.js
sudo npm init
# fillup the relevant details
sudo npm install socket.io@0.9.x --save
sudo npm install mysql --save
# 2. (optional) If still, there's error, check if the NODE_BIN_DIR is set correctly in  /etc/init.d/nodejs-socket-io. 
# It should match with:
which node
# 3. (Optional) If you made changes in the nodejs-socket-io file, remove and add init.d scripts again
sudo update-rc.d -f nodejs-socket-io remove
sudo update-rc.d nodejs-socket-io defaults
```

**Comment by digawp** [comment]
@msemple1111 is the above fixed your issue? Can this be closed?

**Comment by msemple1111** [comment]
Yes azorac's fix solved the issue
