### ISSUE TITLE
Install issue with NPM

### ISSUE THREAD

**Issue by AlesMenzel** [socketio/socket.io#2277]
Running the install with administartive permissions.

```
C:\WINDOWS\system32>npm install socket.io

> utf-8-validate@1.2.1 install C:\Users\Aleš\AppData\Roaming\npm\node_modules\so
cket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild

/
C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\
node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (
node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modu
les\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket.io\node_modul
es\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok

> bufferutil@1.2.1 install C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket
.io\node_modules\engine.io\node_modules\ws\node_modules\bufferutil
> node-gyp rebuild


C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket.io\node_modules\engine.io\
node_modules\ws\node_modules\bufferutil>if not defined npm_config_node_gyp (node
 "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket.io\node_modul
es\engine.io\node_modules\ws\node_modules\bufferutil
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> bufferutil@1.2.1 install C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket
.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules\ws\
node_modules\bufferutil
> node-gyp rebuild


C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-
client\node_modules\engine.io-client\node_modules\ws\node_modules\bufferutil>if
not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\
bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (
node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket.io\node_modul
es\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\b
ufferutil
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1

> utf-8-validate@1.2.1 install C:\Users\Aleš\AppData\Roaming\npm\node_modules\so
cket.io\node_modules\socket.io-client\node_modules\engine.io-client\node_modules
\ws\node_modules\utf-8-validate
> node-gyp rebuild


C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket.io\node_modules\socket.io-
client\node_modules\engine.io-client\node_modules\ws\node_modules\utf-8-validate
>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\
npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  el
se (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:116:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node
-gyp\lib\configure.js:71:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket.io\node_modul
es\socket.io-client\node_modules\engine.io-client\node_modules\ws\node_modules\u
tf-8-validate
gyp ERR! node -v v4.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
socket.io@1.3.7 C:\Users\Aleš\AppData\Roaming\npm\node_modules\socket.io
├── debug@2.1.0 (ms@0.6.2)
├── has-binary-data@0.1.3 (isarray@0.0.1)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2,
 benchmark@1.0.0, json3@3.2.6)
├── socket.io-adapter@0.3.1 (object-keys@1.0.1, debug@1.0.2, socket.io-parser@2.
2.2)
├── engine.io@1.5.4 (base64id@0.1.0, debug@1.0.3, engine.io-parser@1.2.2, ws@0.8
.0)
└── socket.io-client@1.3.7 (to-array@0.1.3, debug@0.7.4, indexof@0.0.1, componen
t-bind@1.0.0, backo2@1.0.2, object-component@0.0.3, component-emitter@1.1.2, has
-binary@0.1.6, parseuri@0.0.2, engine.io-client@1.5.4)

C:\WINDOWS\system32>
```

**Comment by AlesMenzel** [comment]
Same issue: gyp ERR! configure error - Phyton required? #2272
