### ISSUE TITLE
Emit function crash if my data contain a toJSON attribute

### ISSUE THREAD

**Issue by jderuere** [socketio/socket.io#2284]
Hello,

I'm using socket.io 1.3.7:
When I'm doing :
      io.to(channel).emit('subject', { toJSON: '{\"myString\": \"As Json\"}' });

I receive this :

TypeError: obj.toJSON is not a function
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:43:19)
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:47:40)
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:47:40)
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:47:40)
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:37:15)
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:47:40)
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:37:15)
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:47:40)
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:47:40)
    at _hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:37:15)
    at hasBinary (/home/jderuere/Repository/pup/pup-activity-logging/node_modules/socket.io/node_modules/has-binary-data/index.js:56:10)
    at Namespace.emit (/my-project/node_modules/socket.io/lib/namespace.js:210:9)

I think it should be :
 if (obj.toJSON && typeof obj.toJSON == 'function')

Thanks for all the works.

**Comment by jderuere** [comment]
Sorry didn't realize it was a has-binary-data module problem.

**Comment by jderuere** [comment]
Since I did a pull request to the has-binary-data and have no feedback from them. I suggest you to investigate and maybe think of using something else.

**Comment by darrachequesne** [comment]
Hi! I think you found an edge-case here, thanks for the report!

Yet, as the module has-binary-data is maintened by the same persons as socket.io, I think we'll have to wait for your pull request https://github.com/Automattic/has-binary/pull/4 to be merged and the package here bumped.

PS: could you reduce your PR to a single commit?

**Comment by jderuere** [comment]
Hi,

Thanks, I changed my commit, it's clean now.

Thanks for all the work you do on socket.io. It's great!

2015-10-30 4:40 GMT-04:00 Damien Arrachequesne <notifications@github.com>:

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
