### ISSUE TITLE
npm install socket.io gives Visual Studio, and msbuild errors

### ISSUE THREAD

**Issue by op1ekun** [socketio/socket.io#2303]
Running `npm install socket.io`

gives me:

```
> utf-8-validate@1.2.1 install ...\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
> node-gyp rebuild


...\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "c:\bin\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
...\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate\build\validation.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V11 0\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
 ERR! stack     at ChildProcess.onExit (c:\bin\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "c:\\bin\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd ...\node_modules\socket.io\node_modules\engine.io\node_modules\ws\node_modules\utf-8-validate
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
```

ENV:
Windows Server 2012 R2
Visual Studio 2015 Enterprise (with Visual C++ installed - that fixed issue for installing karma)
node  0.12.7

**Comment by op1ekun** [comment]
I've already tried this one http://kevgriffin.com/specifying-visual-studio-version-in-npm-installs/

**Comment by schematical** [comment]
I am running into the same issue on ubuntu starting today....

**Comment by peisenmann** [comment]
I'm getting something similar in Windows 7 (x64). A wall of C++ compile errors followed by
```
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\peisenmann\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\peisenmann\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\
\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\app\node_modules\utf-8-validate
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

**Comment by op1ekun** [comment]
Guys, maybe this is going to help you?
https://github.com/karma-runner/karma/issues/1691

@schematical As for Ubuntu I guess installing gcc should do the trick? I've never run into this kind of troubles while on linux.

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
