### ISSUE TITLE
Error with example chat

### ISSUE THREAD

**Issue by ParrotCraft** [socketio/socket.io#2362]
I got an error with using example chat :(
I'm using node  v5.3.0.
```
module.js:328
    throw err;
    ^

Error: Cannot find module '../..'
    at Function.Module._resolveFilename (module.js:326:15)
    at Function.Module._load (module.js:277:25)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/root/socket/index.js:5:10)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)
```

**Comment by rauchg** [comment]
Can you paste the whole contents of the file?

**Comment by ParrotCraft** [comment]
I just copied the example.
Ok, it's working now.
I just changed require('../..') to require('socket-io')
