### ISSUE TITLE
Error: Cannot find module 'bufferutil'

### ISSUE THREAD

**Issue by snypelife** [socketio/socket.io#2375]
Latest builds started failing on 1.4.1, haven't seen any issues created yet hence this one.
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: Cannot find module 'bufferutil' from '/Users/snypelife/360/utopia/web/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/lib'
    at /Users/snypelife/360/utopia/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/Users/snypelife/360/utopia/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/Users/snypelife/360/utopia/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/Users/snypelife/360/utopia/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/snypelife/360/utopia/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/snypelife/360/utopia/web/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:95:15)

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/opt/nvm/versions/node/v0.12.9/bin/node" "/usr/local/opt/nvm/versions/node/v0.12.9/bin/npm" "i"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! utopia@2.4.0 postinstall: `./node_modules/gulp/bin/gulp.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the utopia@2.4.0 postinstall script './node_modules/gulp/bin/gulp.js'.
npm ERR! This is most likely a problem with the utopia package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/gulp/bin/gulp.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls utopia
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/snypelife/360/utopia/web/npm-debug.log
```

**Comment by snypelife** [comment]
nvm this appears to be a socket-io/perhaps engine-io-client/perhaps ws issue.  closing.
