### ISSUE TITLE
Random crash along with mongoose

### ISSUE THREAD

**Issue by Masadow** [socketio/socket.io#2377]
Hi guys, since I installed socket.io, my app is randomly crashing with the following error

    Error: Error getting collection: sessions
    at /home/jdelas/mapV2/node_modules/connect-mongo/lib/connect-mongo.js:160:19
    at Db.collection (/home/jdelas/mapV2/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:526:27)
    at MongoStore._get_collection (/home/jdelas/mapV2/node_modules/connect-mongo/lib/connect-mongo.js:158:17)
    at MongoStore.get (/home/jdelas/mapV2/node_modules/connect-mongo/lib/connect-mongo.js:222:10)
    at session (/home/jdelas/mapV2/node_modules/express-session/index.js:367:11)
    at Array.<anonymous> (/home/jdelas/mapV2/config/socket.js:8:40)
    at run (/home/jdelas/mapV2/node_modules/socket.io/lib/namespace.js:116:11)
    at Namespace.run (/home/jdelas/mapV2/node_modules/socket.io/lib/namespace.js:128:3)
    at Namespace.add (/home/jdelas/mapV2/node_modules/socket.io/lib/namespace.js:157:8)
    at Client.connect (/home/jdelas/mapV2/node_modules/socket.io/lib/client.js:75:20)
    at Server.onconnection (/home/jdelas/mapV2/node_modules/socket.io/lib/index.js:318:10)
    at emitOne (events.js:77:13)
    at Server.emit (events.js:169:7)
    at Server.handshake (/home/jdelas/mapV2/node_modules/engine.io/lib/server.js:308:8)
    at /home/jdelas/mapV2/node_modules/engine.io/lib/server.js:212:12
    at Server.checkRequest (/home/jdelas/mapV2/node_modules/socket.io/lib/index.js:68:51)

Any clue about it ?

It mostly happen when I try to restart the server and there was an opened socket.io connection. This means if I will ever need to restart the server in production, I won't be able to do so until every users close their tab cotaining my app in their browser :/

**Comment by Masadow** [comment]
Ok, I figured out that I had to put socket.io stuff under `mongoose.connection.on('connected', function () { });` to make sure it's running before starting
