### ISSUE TITLE
TypeError: Cannot read property \'removeListener\' of null

### ISSUE THREAD

**Issue by btmdave** [socketio/socket.io#2390]
I'm getting this error in 1.4.4.   Any ideas what could be causing this?
```
[ 'TypeError: Cannot read property \'removeListener\' of null',
     '    at cleanup (/var/www/app/server/node_modules/socket.io/node_modules/engine.io/lib/socket.js:232:14)',
     '    at onError (/var/www/app/server/node_modules/socket.io/node_modules/engine.io/lib/socket.js:240:5)',
     '    at Socket.onClose (/var/www/app/server/node_modules/socket.io/node_modules/engine.io/lib/socket.js:250:5)',
     '    at Socket.g (events.js:199:16)',
     '    at Socket.emit (events.js:129:20)',
     '    at Socket.onClose (/var/www/app/server/node_modules/socket.io/node_modules/engine.io/lib/socket.js:303:10)',
     '    at WebSocket.g (events.js:199:16)',
     '    at WebSocket.emit (events.js:129:20)',
     '    at WebSocket.Transport.onClose (/var/www/app/server/node_modules/socket.io/node_modules/engine.io/lib/transport.js:115:8)',
     '    at WebSocket.g (events.js:199:16)',
     '    at WebSocket.emit (events.js:110:17)',
     '    at WebSocket.cleanupWebsocketResources (/var/www/app/server/node_modules/socket.io/node_modules/engine.io/node_modules/ws/lib/WebSocket.js:927:10)',
     '    at Socket.emit (events.js:129:20)',
     '    at _stream_readable.js:908:16',

```

This seems to occur on disconnect.

**Comment by btmdave** [comment]
Closing this, did a clean npm install, fixed whatever the issue was.
