### ISSUE TITLE
does socket.io is not the proper version?

### ISSUE THREAD

**Issue by jdzyzh** [socketio/socket.io#2394]
var io = socketIO.listen(server);
function describeRoom(name) {
        var adapter = io.nsps['/'].adapter;
        
        var clients = adapter.rooms[name] || {};       
        var result = {
            clients: {}
        };
        Object.keys(clients).forEach(function (id) {        	  
            result.clients[id] = adapter.nsp.connected[id].resources;
        });
        return result;
    }

Missing error handler on socket.
TypeError: Cannot read property 'resources' of undefined
at D:\Program Files\nodejs\signalmaster-master\sockets.js:157:59
at Array.forEach (native)
at describeRoom (D:\Program Files\nodejs\signalmaster-master\sockets.js:156:
30)
at Socket.join (D:\Program Files\nodejs\signalmaster-master\sockets.js:70:30
)
at emitTwo (events.js:87:13)
at Socket.emit (events.js:172:7)
at Socket.onevent (D:\Program Files\nodejs\node_modules\socket.io\lib\socket
.js:335:8)
at Socket.onpacket (D:\Program Files\nodejs\node_modules\socket.io\lib\socke
t.js:295:12)
at Client.ondecoded (D:\Program Files\nodejs\node_modules\socket.io\lib\clie
nt.js:193:14)
at Decoder.Emitter.emit (D:\Program Files\nodejs\node_modules\component-emit
ter\index.js:134:20)

**Comment by jdzyzh** [comment]
socket.io   verison 1.4.4

**Comment by nkzawa** [comment]
The result of `adapter.rooms[name]` is not an object on 1.4.0 or later. and it should be a private property anyway.
