### ISSUE TITLE
Error socket.io

### ISSUE THREAD

**Issue by mfaridii** [socketio/socket.io#2442]
## code server ->

var app = require('express')();
var http = require('http').Server(app);
var io = require('socket.io')(http);

var numuser = 0;
var max = 0;
app.get('/', function(req, res){
  res.sendfile('index.html');
});
io.on('connection',function(socket){

```
numuser ++;
if(max < numuser){
    max = numuser
}
socket.on('disconnect',function(){
    numuser --;
});
```

 });
http.listen(3333,function(){
    console.log('server listening on port 3333');
})

---

**Error ->**
`C:\Documents and Settings\Administrator\Desktop\node\node_modules\s  ocket.io\node_modules\engine.io\node_modules\ws\li  b\Receiver.js:247
  if (!this.state.fragmentedOperation) this.unfragmentedBufferPool.reset(true);
                 ^

TypeError: Cannot read property 'fragmentedOperation' of null
    at Receiver.endPacket (C:\Documents and Settings\Administrator\Desktop\node\
node_modules\socket.io\node_modules\engine.io\node  _modules\ws\lib\Receiver.js:24
7:18)
    at Receiver.opcodes.1.finish (C:\Documents and Settings\Administrator\Deskto
p\node\node_modules\socket.io\node_modules\engine.  io\node_modules\ws\lib\Receive
r.js:483:12)
    at Receiver.<anonymous> (C:\Documents and Settings\Administrator\Desktop\nod
e\node_modules\socket.io\node_modules\engine.io\no  de_modules\ws\lib\Receiver.js:
451:33)
    at Receiver.add (C:\Documents and Settings\Administrator\Desktop\node\node_m
odules\socket.io\node_modules\engine.io\node_modul  es\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (C:\Documents and Settings\Administrator\Desktop\node\
node_modules\socket.io\node_modules\engine.io\node  _modules\ws\lib\WebSocket.js:8
00:20)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:523:20)`

**Comment by auridevil** [comment]
happen the same to me! any fix?

**Comment by nguyenhaian** [comment]
I get exactly the same.

```
D:\NodeApps\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:247
  if (!this.state.fragmentedOperation) this.unfragmentedBufferPool.reset(true);
                 ^

TypeError: Cannot read property 'fragmentedOperation' of null
    at Receiver.endPacket (D:\NodeApps\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:247:18)
    at Receiver.opcodes.1.finish (D:\NodeApps\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:483:12)
    at Receiver.<anonymous> (D:\NodeApps\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:451:33)
    at Receiver.add (D:\NodeApps\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\Receiver.js:95:24)
    at Socket.realHandler (D:\NodeApps\node_modules\socket.io\node_modules\engine.io\node_modules\ws\lib\WebSocket.js:800:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:529:20)

```

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
