### ISSUE TITLE
"Error: Lone surrogate" keeps crashing server, no way to handle it

### ISSUE THREAD

**Issue by artofspeed** [socketio/socket.io#2459]
My `node.js` server gets crashed once per 1 or 2 days due to `Error: Lone surrogate U+D83D is not a scalar value` (in utf8.js file). I suspect this error occurs when client sends corrupt packet data. Is there a way to catch this error **or at least handle it such that the server doesn't crash**? 

This is what's displayed when my server crashes:

```
Error: Lone surrogate U+D83D is not a scalar value
    at Error (native)
    at checkScalarValue (/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/node_modules/utf8/utf8.js:69:10)
    at encodeCodePoint (/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/node_modules/utf8/utf8.js:90:4)
    at Object.utf8encode [as encode] (/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/node_modules/utf8/utf8.js:111:18)
    at Object.exports.encodePacket (/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:74:34)
    at encodeOne (/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:387:13)
    at eachWithIndex (/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:256:5)
    at map (/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:263:5)
    at Object.exports.encodePayloadAsBinary (/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:411:3)
    at Object.exports.encodePayload (/root/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:225:20)
    at XHR.Polling.send (/root/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:238:10)
    at Socket.flush (/root/node_modules/socket.io/node_modules/engine.io/lib/socket.js:341:20)
    at Socket.sendPacket (/root/node_modules/socket.io/node_modules/engine.io/lib/socket.js:317:10)
    at Socket.send.Socket.write (/root/node_modules/socket.io/node_modules/engine.io/lib/socket.js:290:8)
    at writeToEngine (/root/node_modules/socket.io/lib/client.js:148:17)
    at Client.packet (/root/node_modules/socket.io/lib/client.js:159:7)
```

**Comment by calzoneman** [comment]
Reproducible test case:

**server.js**
```javascript
var io = require('socket.io')(4444);

io.on('connection', socket => {
    socket.emit('test', String.fromCharCode(0xd800));
});
```

**client.js**
```javascript
var socket = require('socket.io-client')('ws://localhost:4444');
```

**Comment by calzoneman** [comment]
Version:

```
├─┬ socket.io@1.4.6 
│ └── engine.io@1.6.9 
└─┬ socket.io-client@1.4.6 
  └── engine.io-client@1.6.9 
```

**Comment by calzoneman** [comment]
`utf8` documentation calls out this error condition and says to either sanitize your input or use `wtf-8`: https://github.com/mathiasbynens/utf8.js/blob/d091a55459b4b137dc2e9050554bcfd4800a1a59/README.md#utf8encodestring

**Comment by nuclearace** [comment]
@rauchg @nkzawa What do you think would be the best way to handle this? Drop packets with lone surrogates or strip them out?

**Comment by calzoneman** [comment]
I'm willing to put out a PR to fix this, but I'd also like to know the answer to the above^

The way I see it, there are a few ways this could be handled:

1. Use `wtf-8`, as the README of `utf8` suggests, and support emitting invalid lone surrogates to XHR clients (this is already not a problem for WS clients)
2. Strip lone surrogates prior to encoding
3. Drop packets containing lone surrogates

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/engine.io-parser/pull/68, included in socket.io `1.5.0`.
