### ISSUE TITLE
Error during Server.handleRequest for WebSocket transport

### ISSUE THREAD

**Issue by edufelipe** [socketio/socket.io#2484]
I've been trying to update from 1.2.0 to 1.4.5 for the past couple of hours and I have run into what I believe to be a bug.

The issue boils down to `WebSocket`, defined in `engine.io/lib/transports/websocket.js`, trying to use the attribute `req.websocket` during the `Server.handshake` method triggered by the `"request"` event of the HTTP server.

But this attribute is only set during `Server.handleUpgrade` method, triggered by `"upgrade"` event. Given that the `"upgrade"` event happens **after** the `"request"` event, the WebSocket transport should never work.

This is what I get when running **Socket.IO 1.4.5** on **Node.js 4.4.0** with `export DEBUG=*`:

```
  socket.io:server initializing namespace / +0ms
  socket.io:server creating engine.io instance with opts {"path":"/pubsub"} +5ms
  socket.io:server attaching client serving req handler +4ms
  engine intercepting request for path "/pubsub/" +6s
  engine handling "GET" http request "/pubsub/?EIO=3&transport=websocket" +2ms
  engine handshaking client "foHFt8fT9nZ92ZdOAAAA" +4ms
  TypeError: Cannot read property 'on' of undefined
    at new WebSocket (myapp/node_modules/socket.io/node_modules/engine.io/lib/transports/websocket.js:27:14)
    at Server.handshake (myapp/node_modules/socket.io/node_modules/engine.io/lib/server.js:267:21)
    at myapp/node_modules/socket.io/node_modules/engine.io/lib/server.js:212:12
    at Server.checkRequest (myapp/node_modules/socket.io/lib/index.js:67:51)
    at Server.verify (myapp/node_modules/socket.io/node_modules/engine.io/lib/server.js:153:17)
    at Server.handleRequest (myapp/node_modules/socket.io/node_modules/engine.io/lib/server.js:202:8)
    at Server.<anonymous> (myapp/node_modules/socket.io/node_modules/engine.io/lib/server.js:432:12)
    at Server.<anonymous> (myapp/node_modules/socket.io/lib/index.js:260:16)
    at emitTwo (events.js:87:13)
    at Server.emit (events.js:172:7)
```

This is the server code:

```javascript
var app = require('http').createServer();
var io = require('socket.io')(app, {path: '/pubsub'});

io.use(function(socket, next) {
  console.log('allowing connection to continue');
  next();
});

io.on('connection', function(socket) {
  console.log('got socket', socket);
});

app.listen(3131);
```

And this is the client code:

```
var socket = io({path: '/pubsub', transports:['websocket']});

socket.on('connect', function() {
  console.log("connected");
});

socket.on('message', function(data) {
  console.log("got message", data);
});
```

Am I missing something?

**Comment by edufelipe** [comment]
Turns out I was interpreting things wrong. The `upgrade` events always come before the `request` event, so the whole issue was a misconfiguration on uWSGI that was causing it to send a `Connection: close` headers regardless of whether it was proxying a websocket or not.

Why it was working before I upgraded to 1.4.5 I do not know, but everything is now working as expected.
