### ISSUE TITLE
uncaughtException, AssertionError: false == true

### ISSUE THREAD

**Issue by joakimrapp** [socketio/socket.io#2501]
Sorry for not having too much details, but got this from our logs:

AssertionError: false == true
    at ServerResponse.<anonymous> (http.js:2130:7)
    at ServerResponse.emit (events.js:92:17)
    at ServerResponse.OutgoingMessage._finish (http.js:1070:8)
    at ServerResponse.OutgoingMessage.end (http.js:1053:10)
    at respond (/opt/socket-srv/node_modules/http-socket/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:321:14)
    at XHR.Polling.doWrite (/opt/socket-srv/node_modules/http-socket/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:290:5)
    at XHR.Polling.write (/opt/socket-srv/node_modules/http-socket/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:265:8)
    at /opt/socket-srv/node_modules/http-socket/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:250:10
    at /opt/socket-srv/node_modules/http-socket/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:221:12
    at proxy (/opt/socket-srv/node_modules/http-socket/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/node_modules/after/index.js:23:13)

Happened 6 times on 6 different servers, have not seen it before and we had no new deploys of the servers prior to the issue.

best regards J.

**Comment by hisune** [comment]
I have the same problem.
my socket.io version is 1.4.5
```
AssertionError: false == true
    at ServerResponse.resOnFinish (_http_server.js:457:7)
    at ServerResponse.emit (events.js:104:17)
    at ServerResponse.OutgoingMessage._finish (_http_outgoing.js:572:8)
    at ServerResponse._finish (_http_server.js:118:37)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:563:10)
    at respond (/chat/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:321:14)
    at XHR.Polling.doWrite (/chat/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:290:5)
    at XHR.Polling.write (/chat/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:265:8)
    at /chat/node_modules/socket.io/node_modules/engine.io/lib/transports/polling.js:250:10
    at /chat/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:221:12
    at proxy (/chat/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/node_modules/after/index.js:23:13)
    at /chat/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:236:7
    at /chat/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:216:7
    at Object.exports.encodePacket (/chat/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:78:10)
    at encodeOne (/chat/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:215:13)
    at eachWithIndex (/chat/node_modules/socket.io/node_modules/engine.io/node_modules/engine.io-parser/lib/index.js:234:5)
```

**Comment by driedger** [comment]
What version of nodejs binary are you using? I had similar issues, and resolved by updating from an earlier release of 4.x to the current LTS version of 4.4.3

**Comment by darrachequesne** [comment]
That issue was closed automatically. Please check if your issue is fixed with the latest release, and reopen if needed (with a [fiddle](https://github.com/darrachequesne/socket.io-fiddle) reproducing the issue if possible).
