### ISSUE TITLE
 (HTTPLog)-Static: isSBSettingEnabled false oom

### ISSUE THREAD

**Issue by ChocolateTan** [socketio/socket.io#2904]
FATAL EXCEPTION: EventThread
                                                               Process: com.ziines.it, PID: 25951
                                                               java.lang.OutOfMemoryError: pthread_create (1040KB stack) failed: Try again
                                                                   at java.lang.Thread.nativeCreate(Native Method)
                                                                   at java.lang.Thread.start(Thread.java:1063)
                                                                   at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
                                                                   at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:503)
                                                                   at java.util.concurrent.Executors$DelegatedScheduledExecutorService.schedule(Executors.java:644)
                                                                   at io.socket.engineio.client.Socket.setPing(Socket.java:565)
                                                                   at io.socket.engineio.client.Socket.onHandshake(Socket.java:529)
                                                                   at io.socket.engineio.client.Socket.onPacket(Socket.java:499)
                                                                   at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
                                                                   at io.socket.engineio.client.Socket$5.call(Socket.java:313)
                                                                   at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                   at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
                                                                   at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
                                                                   at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
                                                                   at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
                                                                   at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
                                                                   at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
                                                                   at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
                                                                   at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                   at java.lang.Thread.run(Thread.java:818)

i connect many different namespace without mange.class.
when i request api(not socketio) will log many (HTTPLog)-Static: isSBSettingEnabled false.
finally, oom

**Comment by darrachequesne** [comment]
Please open an issue here: https://github.com/socketio/socket.io-client-java
