### ISSUE TITLE
Electron打包的时候调用Socket.io出错。

### ISSUE THREAD

**Issue by ZililuYa** [socketio/socket.io#2943]
App threw an error during load
Error: Cannot find module "."
    at D:\Web\electron-chat-room\app\webpack:\~\_socket.io@2.0.1@socket.io\lib\index.js:109:1
    at me (D:\Web\electron-chat-room\app\webpack:\~\_socket.io@2.0.1@socket.io\lib\index.js:110:1)
    at G.serveClient (D:\Web\electron-chat-room\app\webpack:\~\_socket.io@2.0.1@socket.io\lib\index.js:112:1)
    at new G (D:\Web\electron-chat-room\app\webpack:\~\_socket.io@2.0.1@socket.io\lib\index.js:51:1)
    at G (D:\Web\electron-chat-room\app\webpack:\~\_socket.io@2.0.1@socket.io\lib\index.js:58:1)
    at Object../app/main.dev.js (D:\Web\electron-chat-room\app\webpack:\app\main.dev.js:132:11)
    at I (D:\Web\electron-chat-room\app\webpack:\webpack\bootstrap 573266dda1c4b3b9841b:36:44)
    at Object.17 (D:\Web\electron-chat-room\app\main.prod.js:16:1025)
    at I (D:\Web\electron-chat-room\app\webpack:\webpack\bootstrap 573266dda1c4b3b9841b:36:44)
    at D:\Web\electron-chat-room\app\webpack:\webpack\bootstrap 573266dda1c4b3b9841b:65:1

Why?

**Comment by darrachequesne** [comment]
Could you please provide a way to reproduce the issue?

**Comment by nesfe** [comment]
Ok。

这是我的项目入口JS：
https://github.com/nesfe/electron-LAN-chat/blob/master/app/main.dev.js

``` js
import { app, BrowserWindow, ipcMain } from 'electron';
import MenuBuilder from './menu';

let mainWindow = null;
if (process.env.NODE_ENV === 'production') {
  const sourceMapSupport = require('source-map-support');
  sourceMapSupport.install();
}

if (process.env.NODE_ENV === 'development' || process.env.DEBUG_PROD === 'true') {
  require('electron-debug')();
  const path = require('path');
  const p = path.join(__dirname, '..', 'app', 'node_modules');
  require('module').globalPaths.push(p);
}

const installExtensions = async () => {
  const installer = require('electron-devtools-installer');
  const forceDownload = ! ! process.env.UPGRADE_EXTENSIONS;
  const extensions = [
    'REACT_DEVELOPER_TOOLS',
    'REDUX_DEVTOOLS'
  ];

  return Promise
    .all(extensions.map(name => installer.default(installer[name], forceDownload)))
    .catch(console.log);
};


/**
 * Add event listeners...
 */

app.on('window-all-closed', () => {
  // Respect the OSX convention of having the application in memory even
  // after all windows have been closed
  if (process.platform !== 'darwin') {
    app.quit();
  }
});


app.on('ready', async () => {
  if (process.env.NODE_ENV === 'development' || process.env.DEBUG_PROD === 'true') {
    // await installExtensions();
  }

  mainWindow = new BrowserWindow({
    // show: false,
    width: 900,
    height: 650,
    minWidth: 900,
    minHeight: 650,
    frame: false
  });

  mainWindow.loadURL(`file://${__dirname}/app.html`);

  // @TODO: Use 'ready-to-show' event
  //        https://github.com/electron/electron/blob/master/docs/api/browser-window.md#using-ready-to-show-event
  mainWindow.webContents.on('did-finish-load', () => {
    if (! mainWindow) {
      throw new Error('"mainWindow" is not defined');
    }
    mainWindow.show();
    mainWindow.focus();
  });

  mainWindow.show();

  // 调试
  // mainWindow.webContents.openDevTools();

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  const menuBuilder = new MenuBuilder(mainWindow);
  menuBuilder.buildMenu();


  // 关闭
  ipcMain.on('close', (event, arg) => {
    app.quit();
  });
  // 最大化
  ipcMain.on('max', (event, arg) => {
    mainWindow.isMaximized() ? mainWindow.unmaximize() : mainWindow.maximize();
    // win.setFullScreen(true);
  });
  // 最小化
  ipcMain.on('min', (event, arg) => {
    mainWindow.minimize();
  });

});

// import Express  from 'express';
// let apps = Express();
// let server = require('http').Server(apps);
//
// import Socket  from 'socket.io';
//
// console.log(Socket);
// let io = Socket(server);
// server.listen(19964);
// io.on('connection', (socket) => {
//   socket.on('news', (data) => {
//     mainWindow.webContents.send('news', data);
//   });
// });

let io = require('socket.io')();
io.on('connection', (socket) => {
  socket.on('news', (data) => {
    mainWindow.webContents.send('news', data);
  });
});
io.listen(19964);
``` 

运行 
``` bash
npm start
``` 
就会报错，找不到 模型  "."     郁闷。。。


打包其他的扩展是没有问题，包括  React、Electron 等等

**Comment by haschu** [comment]
I have the exact same problem. @nesfe did you figure out how to solve it?

**Comment by crylg** [comment]
WebSocket connection to 'ws://12.12.32.11:3000/socket.io/?EIO=3&transport=websocket' failed: Error during WebSocket handshake: Unexpected response code: 400
额遇到过这种问题吗

**Comment by mmclau14** [comment]
I have the error in the same place. any progress on this?

**Comment by darrachequesne** [comment]
Disabled the client serving should fix the issue:

```js
let io = require('socket.io')({
  serveClient: false
});
```

It seems Webpack has trouble bundling the client file (`socket.io.js`) that is served by default.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
