### ISSUE TITLE
Azure  socket io ^2.0.0

### ISSUE THREAD

**Issue by ittesla** [socketio/socket.io#2947]
Bug when publishing on Azure web app.

Publishing app to azure returns 
'The page cannot be displayed because an internal server error has occurred.'
when socket io version is ^2.0.0
If i put 1.7.x version it works  fine.Maybe I did something wrong, i am just leaving this as heads up

Log from web app :

Thu May 18 2017 16:25:15 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
TypeError: Object #<Object> has no method '_extend'
    at Function.init (D:\home\site\wwwroot\node_modules\socket.io-client\node_modules\debug\src\node.js:234:28)
    at createDebug (D:\home\site\wwwroot\node_modules\socket.io-client\node_modules\debug\src\debug.js:124:13)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\socket.io-client\lib\url.js:7:28)
    at Module._compile (module.js:446:26)
    at Object..js (module.js:464:10)
    at Module.load (module.js:353:31)
    at Function._load (module.js:311:12)
    at Module.require (module.js:359:17)
    at require (module.js:375:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\socket.io-client\lib\index.js:6:11)

**Comment by darrachequesne** [comment]
@ittesla it seems that the issue was fixed in debug: https://github.com/visionmedia/debug/issues/452
