### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by hnphi** [socketio/socket.io#2968]
* **Version**: v.6.9.5
* **Platform**: WINDOW 7 64-bit
* **Subsystem**: Socket.io ~ v1.7.3

All emit in server.js look like:

```js
var n = "test";
var pack = new SendMsg(2 + n.length);
pack.writeString(n);
socket.emit("key", pack.dataView.buffer)
```

function SendMsg [at here](https://raw.githubusercontent.com/pomega/pomega/master/sendmsg.js)

Sometime I got this error when app running.

```
buffer.js:262
  throw new TypeError(kFromErrorMsg);
  ^
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at arrayBufferToBuffer (C:\wamp\www\puble.io\server\node_modules\engine.io-parser\lib\index.js:371:16)
    at Object.exports.encodePacket (C:\wamp\www\puble.io\server\node_modules\engine.io-parser\lib\index.js:66:19)
    at WebSocket.send (C:\wamp\www\puble.io\server\node_modules\engine.io\lib\transports\websocket.js:94:12)
    at Socket.flush (C:\wamp\www\puble.io\server\node_modules\engine.io\lib\socket.js:424:20)
    at emitNone (events.js:91:20)
    at WebSocket.emit (events.js:185:7)
    at onEnd (C:\wamp\www\puble.io\server\node_modules\engine.io\lib\transports\websocket.js:120:10)
```

**Comment by escaip** [comment]
I've encountered the same problem. the fix is easy `socket.emit("key", Buffer.from(pack.dataView.buffer))`, but it should work without it. I guess that's just a minor bug.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
