### ISSUE TITLE
Cannot read property 'sockets' of undefined

### ISSUE THREAD

**Issue by Nerfair** [socketio/socket.io#3004]
Socket.io 2.0.1, with stable online of 4000 sockets 24/7, there is about 1-2 times a day when i am getting 

```
TypeError: Cannot read property 'sockets' of undefined
--
at /srv/www/socket/server/server.js:178:64
at normal_reply (/srv/www/socket/server/node_modules/redis/index.js:721:21)
at RedisClient.return_reply (/srv/www/socket/server/node_modules/redis/index.js:819:9)
at JavascriptRedisParser.returnReply (/srv/www/socket/server/node_modules/redis/index.js:192:18)
at JavascriptRedisParser.execute (/srv/www/socket/server/node_modules/redis-parser/lib/parser.js:574:12)
at Socket.<anonymous> (/srv/www/socket/server/node_modules/redis/index.js:274:27)
at emitOne (events.js:96:13)
at Socket.emit (events.js:191:7)
at readableAddChunk (_stream_readable.js:178:18)
at TCP.onread (net.js:561:20)
```

code triggering this fatal is

```
                if (response && !!io.sockets && !!io.sockets.adapter.rooms[roomUid].sockets) {
                    var clients = io.sockets.adapter.rooms[roomUid].sockets;
                    for (var clientUid in clients) {
                        var clientSocket = io.sockets.connected[clientUid];
                        if (clientSocket.jwt.user.id == socket.jwt.user.id) {
                            clientSocket.emit('leave', roomUid);
                        }
                    }
                }
```

but i can't figure out why, more of this, error triggered after checking for response and existence of io.sockets, how it passes this if, no idea.

**Comment by darrachequesne** [comment]
@Nerfair for future readers, could you please explain how you fixed the issue?
