### ISSUE TITLE
Will the computer demo (socket.computer) ever be fixed?

### ISSUE THREAD

**Issue by MDMCK10** [socketio/socket.io#3006]
Edit 2018: no activity on issue since 1 year, site is now completely down
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour

It's dead, or just simply stuck on the same screen, i'm not sure how many months this has been happening for, but it's a lot.

### Steps to reproduce (if the current behaviour is a bug)

Just go to the site [here](http://socket.computer)

### Expected behaviour

For it to actually work, and be alive

### Setup
- OS: Windows
- browser: Chrome
- socket.io version: since it's a bug with the demo, i'm unsure about this.

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

I have also posted a issue [here](https://github.com/kevin-roark/socket.io-computer/issues/16) about this, so if this doesn't belong here, feel free to close it.

**Comment by darrachequesne** [comment]
The demo has indeed been down for a while. If someone would like to spend some time to dockerize it (source code is here: https://github.com/rauchg/socket.io-computer), I'll be happy to host it on now.sh with the other demos.

**Comment by Osein** [comment]
It gives CONTENT_LENGTH_MISMATCH. Build.js is not loading at all. Maybe express or some kind of special character error?

**Comment by MDMCK10** [comment]
any updates on this?

**Comment by MDMCK10** [comment]
okay, i'm looking into dockerizing this, things are looking good so far, but i've ran into multiple issues:
1. ran out of disk space, ugh.
2. node-gyp configure build failed for jpeg@2.0.0
for 2, i think i just need to use an older nodejs version... but which one?
@darrachequesne

**Comment by Osein** [comment]
Can you post log for 2?

**Comment by MDMCK10** [comment]
here is the log: https://pastebin.com/amWPUp4U
and here is my dockerfile: https://pastebin.com/PECMwGZ2
@Osein

**Comment by MDMCK10** [comment]
![image](https://user-images.githubusercontent.com/21245760/29268074-944f88d4-80eb-11e7-864d-764051791083.png)
I'M SO CLOSE TO MAKING IT WORK AA

**Comment by MDMCK10** [comment]
okay now i'm a bit confused here
`
user@vps416580:~/stuf$ docker run -p 5000:5000 mdmck10/socketcomputer-test
Formatting 'winxp.img', fmt=qcow2 size=3221225472 encryption=off cluster_size=65   536 lazy_refcounts=off
listening on *:5000

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED
    at RedisClient.on_error (/app/node_modules/redis/index.js:185:24)
    at Socket.<anonymous> (/app/node_modules/redis/index.js:95:14)
    at Socket.emit (events.js:95:17)
    at net.js:441:14
    at process._tickCallback (node.js:458:13)
user@vps416580:~/stuf$
`
Dockerfile: https://paste.ee/p/7jr7c

**Comment by MDMCK10** [comment]
Okay so i got everything to work, now when i run it, it runs fine, although when i try to visit <site>:5000, it just doesn't work, gives a ERR_CONNECTION_REFUSED, i exposed the ports 5000 and 6379, do i need to expose anything else or do anything else? @darrachequesne @Osein

**Comment by Osein** [comment]
Socket code is trying to connect into localhost:6001

**Comment by MDMCK10** [comment]
i tried to go there from the vps itself (using vnc), all i got was "the connection was reset", nothing useful as always.
@Osein

**Comment by Osein** [comment]
For me the problem is io.js is not working at all. No listening app is writed on console for io

Starting redis-server: redis-server.
Formatting 'winxp.img', fmt=qcow2 size=3221225472 encryption=off cluster_size=65536 lazy_refcounts=off
listening on app *:5000

**Comment by MDMCK10** [comment]
well once i start the docker container, there is no output, at all

**Comment by Osein** [comment]
https://pasteboard.co/GFBPNsK.png

😎

Dockerfile:

FROM ubuntu:14.04
WORKDIR ./app
COPY package.json .
RUN apt update && apt install -y curl wget
RUN curl -sL https://deb.nodesource.com/setup_0.10 | sudo bash -
RUN apt install -y nodejs libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++ redis-server qemu
RUN npm install
COPY . .
RUN wget http://darkok.ml/winxp.iso
EXPOSE 8080
CMD service redis-server start && qemu-img create -f qcow2 winxp.img 3G && COMPUTER_IO_URL=http://192.168.99.100:6001 node app.js && node io.js && COMPUTER_ISO=winxp.iso COMPUTER_IMG=winxp.img node qemu.js

Command:
docker run -p 5000:5000 -p 6001:6001 image_tag

**Comment by MDMCK10** [comment]
thanks.

**Comment by MDMCK10** [comment]
actually, i got it to run, but it's just a black screen, nothing else. hmm

**Comment by Osein** [comment]
then the qemu processes are not working

run docker exec -it "containerid" /bin/bash to get inside container with 3 terminals

# io server
$ node io.js

# qemu instance
$ COMPUTER_ISO=winxp.iso COMPUTER_IMG=winxp.img node qemu.js

# emulator communication process
$ COMPUTER_IMG=winxp.img node emu-runner.js

run this commands on each one and try it

**Comment by computernewb** [comment]
I would be willing to host a mirror of this to host for now.sh. What would I have to do exactly in order to do this?

**Comment by MDMCK10** [comment]
owo it's a dartz (@computernewb)

**Comment by MDMCK10** [comment]
@computernewb okay, here is how you actually do it:
1. install nodejs and npm
2. https://zeit.co/download
3. go in a terminal/command prompt, and run "npm i now -g"
4. git clone https://github.com/rauchg/socket.io-computer
5. download this: https://pastebin.com/raw/u5PE12WB and save it as Dockerfile in the same folder as you cloned the repo to
6. type "now"
7. select 2 for dockerfile (not 1 for npm's package.json)  
8. wait
9. ???
10. it might work

**Comment by MDMCK10** [comment]
I've deployed it to now.sh, but as usual, it didn't work. just a black screen. https://socketio-computer-test.now.sh/
@Osein what am i doing wrong here? :/

**Comment by MDMCK10** [comment]
updated dockerfile, try this if the other one didn't work: https://hastebin.com/raw/juminuhifo

**Comment by Osein** [comment]
As I said try installing supervisor inside to make things work automatically. That long cmd wasnt working for me.

**Comment by MDMCK10** [comment]
@Osein how would i do that with now.sh though

**Comment by computernewb** [comment]
I have successfully deployed socket.computer to now.sh. However, there is an issue. 

I would like to run the VM on my own server, so it can be at an acceptable speed. However, the now.sh website is HTTPS, and I am not sure if it's possible to load config.io through HTTPS. You cannot mix HTTP/HTTPS unless you have security features disabled.

Regardless, if anyone wants to try out the mirror now, it is available here: http://sockcomputer.ml:5000/

**Comment by MDMCK10** [comment]
@computernewb just gonna quickly say this, the mirror is down, it would be great if you could like start that again because i actually want to try it.

**Comment by 6-9-6-9** [comment]
This Dockerfile works a bit better for now.sh: https://hastebin.com/raw/oyudalutet

I noticed you were using && for the node commands, which executes one after the other, and of course the commands don't finish at all, so that's probably why io.js wasn't running. I put the node commands in parenthesis and used a single & for them. It brought me into the windows xp setup: https://socketio-computer-zrsdjjzrfa.now.sh/

I still have to refresh it to update the image and I still can't take turns...

**Comment by 6-9-6-9** [comment]
FINALLY figured it out. You need TWO now.sh images to make this work (the ip detection just returned the ip for regular now.sh). One runs the emulator and is exposed on port 6001 while the other one (the one you go to to see the screen) just runs the app and is exposed on port 5000. The Dockerfile I used for the first one is https://hastebin.com/raw/otawoditic and the Dockerfile I used for the second one is https://hastebin.com/raw/vareleyuye (be sure to replace <insert now.sh url here> with the now.sh url of the first image, without the :6001). Be sure to go to the now.sh url of the second image when done. My deployment is up at https://socketio-computer-wfbhdrhhii.now.sh/

**Comment by computernewb** [comment]
My next advice is to add an hda to the hard drive with Windows XP installed, and use the -snapshot parameter and make a script which restarts QEMU every 15 minutes (or an hour, preferably, since I think 15 minutes is way too short) to simulate the old socket.computer restore system.

@darrachequesne The demo has been successfully deployed,

**Comment by 6-9-6-9** [comment]
OK, I'll edit the Dockerfile to wget a preinstalled XP image and I'll edit qemu.js to include -snapshot.

**Comment by MDMCK10** [comment]
aaaand it never happened

**Comment by computernewb** [comment]
If anyone wants a socket.computer-like environment to use in the meantime, I have a similar site available at http://computernewb.com/collab-vm/ - with a similar VM, VM2 (Windows XP).

**Comment by 6-9-6-9** [comment]
I just deployed a 98 version of socket.computer to [sockcomputer.tk](http://sockcomputer.tk/).

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by IAmNotSiob** [comment]
REALLY old issue, but I finally got around to dockerizing the project (with some much, much needed fixes!!) and a upgrade to Socket.IO v4.
