### ISSUE TITLE
Node js Socket.io error

### ISSUE THREAD

**Issue by jeremywu0521** [socketio/socket.io#3049]
*Note*: for support questions, please use one of these channels: [stackoverflow](http://stackoverflow.com/questions/tagged/socket.io) or [slack](https://socketio.slack.com)

### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way to get a quick answer is to provide a failing test case, by forking the following [fiddle](https://github.com/darrachequesne/socket.io-fiddle) for example.

### Setup
- OS:windows 10
- browser:chrome
- socket.io version:2.0.3

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

const WebSocket = require('./lib/WebSocket');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Server.init (H:\.Web minecraft console\node_modules\socket.io\node_modules\engine.io\lib\server.js:115:16)
    at new Server (H:\.Web minecraft console\node_modules\socket.io\node_modules\engine.io\lib\server.js:65:8)
    at Function.attach (H:\.Web minecraft console\node_modules\socket.io\node_modules\engine.io\lib\engine.io.js:123:16)

#####Sorry!About My poor english,I don't know many of the issues question about.My mother language not english,and i only 14 so not very skillful ,sorry!

**Comment by darrachequesne** [comment]
Which version of nodejs are you using? Only versions > 4 are supported.

**Comment by buddha314** [comment]
I am having the same issue.  This is `server.js`

```
var server = require('http').createServer();
var io = require('socket.io')(server);
io.on('connection', function(client){
  client.on('event', function(data){});
  client.on('disconnect', function(){});
});
server.listen(3000);
```

produces

```
node server.js 
/Users/buddha/sandbox/node/node_modules/socket.io/lib/index.js:177
  const keysIterator = this.parentNsps.keys();
  ^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/buddha/sandbox/node/server.js:2:10)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```
with

```
macbuddha:node buddha$ node --version
v0.12.2
```

**Comment by buddha314** [comment]
Ah, so when you said v > 4, you meant `4.0.0`.  Sometimes people mean `0.4.0` and I had `0.12.2`.  Upgrade to `v9.11.1` and it runs nows.

**Comment by darrachequesne** [comment]
@buddha314 `0.4.0` was released in 2011, it's like prehistoric age for Node.JS :smile_cat:

Closing, please reopen if needed!
