### ISSUE TITLE
TypeError: this.adapter.addAll is not a function

### ISSUE THREAD

**Issue by xzk821649509** [socketio/socket.io#3188]
my project use socket.io 2.0.4 socket.io-redis5.2.0

my code
```
const httpServer = require('http').createServer(app);
const io = require('socket.io')(httpServer);
const ioc = require('socket.io-redis');
io.adapter(ioc({ host: socketRedisConfig.host, port: socketRedisConfig.port, password: socketRedisConfig.password}));
```
the error
```
0|server   | TypeError: this.adapter.addAll is not a function
0|server   |     at Socket.join (/home/htdocs/socket/server/node_modules/socket.io/lib/socket.js:244:16)
0|server   |     at Socket.onconnect (/home/htdocs/socket/server/node_modules/socket.io/lib/socket.js:299:8)
0|server   |     at /home/htdocs/socket/server/node_modules/socket.io/lib/namespace.js:171:16
0|server   |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
0|server   |     at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```
why?

**Comment by darrachequesne** [comment]
Does it happen with a fresh install of `socket.io`? I suspect there is a `socket.io-adapter` module in version `<1.1.0` in your node_modules, could you please run `$ npm ls socket.io-adapter`?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
