### ISSUE TITLE
Error in Build And Use!

### ISSUE THREAD

**Issue by QuestionPython** [socketio/socket.io#3221]
$ node -v
-------
*v9.5.0*

$ npm -v
----------
*5.8.0*

[guest@Base]: /home/guest/Gits/socket.io/examples/chat>$ sudo npm install -g engine.io
------------
```
+ engine.io@3.2.0
updated 1 package in 4.643s
```
[guest@Base]: /home/guest/Gits/socket.io/examples/chat>$ sudo npm install -g socket.io
------------
```
+ socket.io@2.1.0
added 39 packages from 34 contributors in 7.375s
```
[guest@Base]: /home/guest/Gits/socket.io/examples/chat>$ npm update -g npm
------------
[guest@Base]: /home/guest/Gits/socket.io/examples/chat>$ sudo npm update -g npm
------------
[guest@Base]: /home/guest/Gits/socket.io/examples/chat>$ node index.js 
------------
```
module.js:557
    throw err;
    ^

Error: Cannot find module 'engine.io'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/guest/Gits/socket.io/lib/index.js:11:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```
[guest@Base]: /home/guest/Gits/socket.io/examples/chat>$ sudo npm install
-------
```
up to date in 0.431s
```
[guest@Base]: /home/guest/Gits/socket.io/examples/chat>$ sudo npm start
-----------
```
> socket.io-chat@0.0.0 start /home/guest/Gits/socket.io/examples/chat
> node index.js

module.js:557
    throw err;
    ^

Error: Cannot find module 'engine.io'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/guest/Gits/socket.io/lib/index.js:11:14)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! socket.io-chat@0.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the socket.io-chat@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-04-10T22_11_54_824Z-debug.log
```

---------------------------

$ sudo cat /root/.npm/_logs/2018-04-10T22_11_54_824Z-debug.log
-----------
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.8.0
3 info using node@v9.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle socket.io-chat@0.0.0~prestart: socket.io-chat@0.0.0
6 info lifecycle socket.io-chat@0.0.0~start: socket.io-chat@0.0.0
7 verbose lifecycle socket.io-chat@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle socket.io-chat@0.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/guest/Gits/socket.io/examples/chat/node_modules/.bin:/home/guest/.opam/system/bin:/home/guest//bin:/home/guest//.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/guest///.rvm/bin:/home/guest/.rvm/bin
9 verbose lifecycle socket.io-chat@0.0.0~start: CWD: /home/guest/Gits/socket.io/examples/chat
10 silly lifecycle socket.io-chat@0.0.0~start: Args: [ '-c', 'node index.js' ]
11 silly lifecycle socket.io-chat@0.0.0~start: Returned: code: 1  signal: null
12 info lifecycle socket.io-chat@0.0.0~start: Failed to exec start script
13 verbose stack Error: socket.io-chat@0.0.0 start: `node index.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:283:16)
13 verbose stack     at EventEmitter.emit (events.js:160:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:160:13)
13 verbose stack     at maybeClose (internal/child_process.js:943:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid socket.io-chat@0.0.0
15 verbose cwd /home/guest/Gits/socket.io/examples/chat
16 verbose Linux 4.14.15-1-ARCH
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v9.5.0
19 verbose npm  v5.8.0
20 error code ELIFECYCLE
21 error errno 1
22 error socket.io-chat@0.0.0 start: node index.js
22 error Exit status 1
23 error Failed at the socket.io-chat@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
