### ISSUE TITLE
WebSocketWriter.writeClose crashes the app

### ISSUE THREAD

**Issue by GurvinderBawa** [socketio/socket.io#3335]
Android app 
using SOCKET.io version 0.5.0
implementation 'com.github.nkzawa:socket.io-client:0.5.0'

i can only see in fabrics crashlytics, the users are facing this crash, but i have no idea why this is coming up, most probably it has something related to  webSocket.Writer.writeClose.
How to fix this ?

 Crashed: OkHttp http://17.176.117.92:3007/socket.io/?EIO=3&transport=websocket&sid=P5vRfdWExfmHPuAAAV WebSocket
       at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:110)
       at com.squareup.okhttp.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:146)
       at com.squareup.okhttp.internal.ws.RealWebSocket.access$100(RealWebSocket.java:31)
       at com.squareup.okhttp.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:74)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

--

Fatal Exception: java.lang.IllegalArgumentException: Code required to include reason.
       at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:110)
       at com.squareup.okhttp.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:146)
       at com.squareup.okhttp.internal.ws.RealWebSocket.access$100(RealWebSocket.java:31)
       at com.squareup.okhttp.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:74)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

**Comment by GurvinderBawa** [comment]
anyone?

**Comment by jido2015** [comment]
Me too!

**Comment by GurvinderBawa** [comment]
@jido2015  make sure you are using the latest okhttp3 version

**Comment by Mr-Ramzan** [comment]
Same!

Fatal Exception: java.lang.IllegalArgumentException

com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose (WebSocketWriter.java:110)
com.squareup.okhttp.internal.ws.RealWebSocket.peerClose (RealWebSocket.java:146)
com.squareup.okhttp.internal.ws.RealWebSocket.access$100 (RealWebSocket.java:31)
com.squareup.okhttp.internal.ws.RealWebSocket$1$2.execute (RealWebSocket.java:74)
com.squareup.okhttp.internal.NamedRunnable.run (NamedRunnable.java:33)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
java.lang.Thread.run (Thread.java:764)

**Comment by GurvinderBawa** [comment]
@Mr-Ramzan  are you using latest okhttp3 dependency ?

**Comment by Mr-Ramzan** [comment]
No, I was not using any explicit okhttp version. I was using nkzawa/socket.io-java-client that was using an old version of okhttp lib. I replaced it with this lib and added explicit Okhttp 3 lib. now everything works fine

**Comment by GurvinderBawa** [comment]
happy to hear.

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socketio.github.io/socket.io-client-java/installation.html
