### ISSUE TITLE
Error: encode error

### ISSUE THREAD

**Issue by blubbll** [socketio/socket.io#3353]
Missing error handler on `socket`.

Error: encode error

    at Socket.onpacket (/rbd/pnpm-volume/c1ed98bc-058d-4af8-a370-0d5113e8e940/node_modules/.registry.npmjs.org/socket.io/2.1.1/node_modules/socket.io/lib/socket.js:344:20)

    at /rbd/pnpm-volume/c1ed98bc-058d-4af8-a370-0d5113e8e940/node_modules/.registry.npmjs.org/socket.io/2.1.1/node_modules/socket.io/lib/client.js:214:16

    at _combinedTickCallback (internal/process/next_tick.js:132:7)

    at process._tickCallback (internal/process/next_tick.js:181:9)

Missing error handler on `socket`.

When using socket.io with IE7 and the socket disconnects, the Serverside socket.io throws the error above.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.

**Comment by green726** [comment]
I have the same error, anyone know how to fix it? This began occurring when I used BigInt to send an integer

**Comment by Domiii** [comment]
I can also confirm, that this happens when trying to send `BigInt`
