### ISSUE TITLE
Code required to include reason.

### ISSUE THREAD

**Issue by BHARGAV8** [socketio/socket.io#3432]
I am use socket/io in my android mobile device but some time it was crashed i have take crash log that shown below but i don't know what is the exact issue.

### Setup
- OS: 6,7,8,9
- browser: mobile device
- socket.io version: 3.14.0

### Other information (e.g. stacktraces, related issues, suggestions how to fix)
Fatal Exception: java.lang.IllegalArgumentException: Code required to include reason.
       at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:110)
       at com.squareup.okhttp.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:146)
       at com.squareup.okhttp.internal.ws.RealWebSocket.closeConnection(RealWebSocket.java:146)
       at com.squareup.okhttp.internal.ws.RealWebSocket.access$000(RealWebSocket.java:31)
       at com.squareup.okhttp.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:74)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by jido2015** [comment]
> I am use socket/io in my android mobile device but some time it was crashed i have take crash log that shown below but i don't know what is the exact issue.
> 
> ### Setup
> * OS: 6,7,8,9
> * browser: mobile device
> * socket.io version: 3.14.0
> 
> ### Other information (e.g. stacktraces, related issues, suggestions how to fix)
> Fatal Exception: java.lang.IllegalArgumentException: Code required to include reason.
> at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:110)
> at com.squareup.okhttp.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:146)
> at com.squareup.okhttp.internal.ws.RealWebSocket.closeConnection(RealWebSocket.java:146)
> at com.squareup.okhttp.internal.ws.RealWebSocket.access$000(RealWebSocket.java:31)
> at com.squareup.okhttp.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:74)
> at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
> at java.lang.Thread.run(Thread.java:761)

I'm facing the same thing

**Comment by ravitashaw** [comment]
Could you please provide any update on this bug?

**Comment by jido2015** [comment]
Unfortunately, I had to switch to firebase.

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
