### ISSUE TITLE
const io = require("socket.io")(http); triggering ...options       ^^^  SyntaxError: Unexpected token ...

### ISSUE THREAD

**Issue by arunwebber** [socketio/socket.io#3500]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behaviour
Desktop/chat/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (Desktop/chat/node_modules/ws/index.js:3:19)

### Steps to reproduce (if the current behaviour is a bug)

**Note**: the best way (and by that we mean **the only way**) to get a quick answer is to provide a failing test case by forking the following [fiddle](https://github.com/socketio/socket.io-fiddle).

### Expected behaviour

*What is expected?*

### Setup
- OS:ubuntu
- browser:chrome
- socket.io version:2.3

### Other information (e.g. stacktraces, related issues, suggestions how to fix)

https://stackoverflow.com/questions/58545352/how-to-fix-syntaxerror-unexpected-token-while-using-socket-io-in-my-local-m

**Comment by darrachequesne** [comment]
For future readers: please make sure to use an up-to-date Node.js version.

Documentation: https://socket.io/docs/v3/server-installation/#Prerequisites
