### ISSUE TITLE
Socket.io issue with multiple Kubernetes pods

### ISSUE THREAD

**Issue by angular-git-user** [socketio/socket.io#3539]
We have our application deployed in Kubernetes with Nginx+ \
When we use just a single replica (pod) the socket.io client establishes connection and receives data.

But when we add multiple pods with load balancing the socket.io client tries to connect and then disconnects quickly with xhr error.

```
[2020-01-16T19:10:50.031Z] ERROR: local server/17108 on TEST: Connection error
  Error: xhr poll error
      at XHR.Transport.onError (C:\Users\TEST\Desktop\Projects\broker-client\node_modules\engine.io-client\lib\transport.js:67:13)
      at Request.<anonymous> (C:\Users\TEST\Desktop\Projects\broker-client\node_modules\engine.io-client\lib\transports\polling-xhr.js:130:10)
      at Request.Emitter.emit (C:\Users\TEST\Desktop\Projects\broker-client\node_modules\component-emitter\index.js:133:20)
      at Request.onError (C:\Users\TEST\Desktop\Projects\broker-client\node_modules\engine.io-client\lib\transports\polling-xhr.js:311:8)
      at Timeout._onTimeout (C:\Users\TEST\Desktop\Projects\broker-client\node_modules\engine.io-client\lib\transports\polling-xhr.js:258:18)
```

**Comment by DRoet** [comment]
I had similar issue in docker swarm which I resolved using the pure websocket transport instead of polling ([docs](https://socket.io/docs/using-multiple-nodes/)):

`transports: ['websocket']`

**Comment by ErenYatkin** [comment]
Socket.io creates initial connection with a HTTP request, then keeps the connection with long polling. As @DRoet said in comments setting `transport: ['websocket']` will force socket.io to use websocket. You need the configure the client settings `transports: ['websocket'], upgrade: false` to force the connection to use websocket by the way.

If you have a socket server instance long polling will not fail, but when you increase the instance number, each request may handled by another pod instead of the pod which created the inital connection because of the load balancer.

**Comment by wbget** [comment]
try this?
https://github.com/socketio/socket.io/blob/47161a65d40c2587535de750ac4c7d448e5842ba/examples/cluster-nginx/nginx/nginx.conf#L28
I use k8s with load balancing, without nginx.
config the sessionAffinity on service
```
service.spec.sessionAffinity = "ClientIP"
```

**Comment by darrachequesne** [comment]
For future readers:

Please see the documentation here: https://socket.io/docs/v3/using-multiple-nodes/
