### ISSUE TITLE
Not working Socket.io in node 8.14

### ISSUE THREAD

**Issue by sugary-sdk** [socketio/socket.io#3541]
### Current behaviour

*What is actually happening?*

/jet/var/nodejs/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/jet/var/nodejs/node_modules/ws/index.js:3:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Server.init (/jet/app/express_js_blank/node_modules/engine.io/lib/server.js:108:27)
    at new Server (/jet/app/express_js_blank/node_modules/engine.io/lib/server.js:65:8)
    at Function.attach (/jet/app/express_js_blank/node_modules/engine.io/lib/engine.io.js:123:16)
    at Server.initEngine (/jet/app/express_js_blank/node_modules/socket.io/lib/index.js:310:21)
    at /jet/app/express_js_blank/node_modules/socket.io/lib/index.js:295:10
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nodejs-restful-apis@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nodejs-restful-apis@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /jet/run/nodejs/npm.cache/_logs/2020-01-24T11_46_41_082Z-debug.log

### Expected behaviour
It will work but not working

### Setup
- OS: AMI LINUX
- browser: na
- socket.io version: 2.3.0

**Comment by PS-Ddevil** [comment]
One of the possible reasons may be that your node/-modules folder do not have the requirements or is not present. if the packages are mentioned in the package,json then you can delete the node_modules folder and then npm install the dependencies.

**Comment by eltharynd** [comment]
as PS-Ddevil said npm install usually installs dependency as well... it appears you either told it not to or it bugged out... whenever i have npm inssues I'd rather just
`rm -rf node_modules/`
to clear them completeley then
`npm install`

obviously npm can only install modules you told him to install in your package.json... you could run 
`npm install --s socket.io`
to install scoket.io with depencencies ans save (--s) them to your package.json

**Comment by darrachequesne** [comment]
For future readers: at least Node.js 10 is now needed.

Documentation: https://socket.io/docs/v3/server-installation/#Prerequisites
