### ISSUE TITLE
Acknowledgement callback failing when using multiple nodes

### ISSUE THREAD

**Issue by chrisandrewcl** [socketio/socket.io#3549]
### You want to:

* [x] report a *bug*
* [ ] request a *feature*

### Current behavior

When running a single socket.io node, ack callbacks emitted from the client behave as expected.

After enabling socket.io-redis adapter to add more nodes, an error is thrown in the server when trying to emit from clients using ack callbacks.

### Steps to reproduce

1. Setup socket.io nodes listening for events with ack callbacks using socket.io-redis
2. Emit from a client with an ack callback
3. The server will throw "Error: Could not encode"

### Expected behaviour

Acks should keep working even on multi nodes setups. 

This could well be an issue in the adapter but since it is being officially supported and I found no information stating that acks are unsupported when in this setup, it seems there is something wrong. 

If it is indeed for some reason unsupported, at least it could be better highlighted in the docs. It would be a shame though since it is a great feature to be lost in such a common setup.

### Setup
- OS: Ubuntu 18.04.4 LTS 
- browser: n/a
- node: 12.14.1
- socket.io version: 2.3.0
- socket.io-redis version: 5.2.0
- socket.io-client version: 2.3.0

### Other information

```
Error: Could not encode
    at _encode (.../node_modules/notepack.io/lib/encode.js:295:9)
    at _encode (.../node_modules/notepack.io/lib/encode.js:182:17)
    at _encode (.../node_modules/notepack.io/lib/encode.js:281:15)
    at _encode (.../node_modules/notepack.io/lib/encode.js:182:17)
    at _encode (.../node_modules/notepack.io/lib/encode.js:281:15)
    at _encode (.../node_modules/notepack.io/lib/encode.js:182:17)
    at Object.encode (.../node_modules/notepack.io/lib/encode.js:301:14)
    at Redis.broadcast (.../node_modules/socket.io-redis/index.js:408:25)
    at Socket.emit (.../node_modules/socket.io/lib/socket.js:171:18)
    at Socket.send.Socket.write (.../node_modules/socket.io/lib/socket.js:208:13)
```

**Comment by chrisandrewcl** [comment]
I am closing it since it was an error on my end. 

I had a middleware forwarding all received events to other servers, but since Socket.io adds the ack function to the event data, I was mistakenly forward the ack function as part of the message.

Sorry about that.
