### ISSUE TITLE
how to fix this.rooms[room].del is not a function

### ISSUE THREAD

**Issue by fairyland0926** [socketio/socket.io#3716]
Socket.adapter.rooms {
  nxWUxz2FTjvyBq93AAAA: Room { sockets: { nxWUxz2FTjvyBq93AAAA: true }, length: 1 },
  dBW30hVpm4ngBSTIAAAB: Room { sockets: { dBW30hVpm4ngBSTIAAAB: true }, length: 1 },
  '1606722627464': Room { sockets: { nxWUxz2FTjvyBq93AAAA: true }, length: 1 }
}
Socket.adapter.rooms {
  nxWUxz2FTjvyBq93AAAA: Room { sockets: { nxWUxz2FTjvyBq93AAAA: true }, length: 1 },
  dBW30hVpm4ngBSTIAAAB: Room { sockets: { dBW30hVpm4ngBSTIAAAB: true }, length: 1 },
  '1606722627464': Room { sockets: { nxWUxz2FTjvyBq93AAAA: true }, length: 1 }
}
F:\20200723(kasino)\20201020\TeenPatti_Backend\node_modules\socket.io-adapter\index.js:100
        this.rooms[room].del(id);
                         ^

TypeError: this.rooms[room].del is not a function
    at Adapter.delAll (F:\20200723(kasino)\20201020\TeenPatti_Backend\node_modules\socket.io-adapter\index.js:100:26)
    at Socket.leaveAll (F:\20200723(kasino)\20201020\TeenPatti_Backend\node_modules\socket.io\lib\socket.js:288:16)
    at Socket.onclose (F:\20200723(kasino)\20201020\TeenPatti_Backend\node_modules\socket.io\lib\socket.js:448:8)
    at Client.onclose (F:\20200723(kasino)\20201020\TeenPatti_Backend\node_modules\socket.io\lib\client.js:254:24)
    at Socket.emit (events.js:322:22)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at Socket.onClose (F:\20200723(kasino)\20201020\TeenPatti_Backend\node_modules\engine.io\lib\socket.js:318:10)
    at Object.onceWrapper (events.js:416:28)
    at WebSocket.emit (events.js:310:20)
    at WebSocket.EventEmitter.emit (domain.js:482:12)
    at WebSocket.Transport.onClose (F:\20200723(kasino)\20201020\TeenPatti_Backend\node_modules\engine.io\lib\transport.js:127:8)
    at Object.onceWrapper (events.js:417:26)
    at WebSocket.emit (events.js:310:20)
    at WebSocket.EventEmitter.emit (domain.js:482:12)
    at WebSocket.emitClose (F:\20200723(kasino)\20201020\TeenPatti_Backend\node_modules\ws\lib\websocket.js:198:10)
    at Socket.socketOnClose (F:\20200723(kasino)\20201020\TeenPatti_Backend\node_modules\ws\lib\websocket.js:886:15)

**Comment by fairyland0926** [comment]
I solved the problem.
