### ISSUE TITLE
Unable to disable CORS (2.4.1)

### ISSUE THREAD

**Issue by rhansen** [socketio/socket.io#3773]
**Describe the bug**

I am trying to follow the instructions for [handling CORS (v2.x)](https://socket.io/docs/v2/handling-cors/) for the situation where the server and client are served from the same site, but socket.io throws "TypeError: Cannot read property 'origin' of undefined".

**To Reproduce**

Socket.IO server version: `2.4.1`
Node.js version: 14.15.4

*Server*

```js
#!/usr/bin/env node
const Server = require('socket.io');
const io = new Server(3000, {});
io.origins((req, callback) => {
  callback(null, req.headers.origin === undefined); // cross-origin requests will not be allowed
});
```

*Client*

```shell
curl "http://localhost:3000/socket.io/?EIO=3&transport=polling"
```

**Expected behavior**

A response that looks like:
```
96:0{"sid":"Lbo5JLzTotvW3g2LAAAA","upgrades":["websocket"],"pingInterval":25000,"pingTimeout":5000}
```

**Actual behavior**

Server crashes:
```
/tmp/test/index.js:5
  callback(null, req.headers.origin === undefined); // cross-origin requests will not be allowed
                             ^

TypeError: Cannot read property 'origin' of undefined
    at Server._origins (/tmp/test/index.js:5:30)
    at Server.checkRequest (/tmp/test/node_modules/socket.io/lib/index.js:75:68)
    at Server.verify (/tmp/test/node_modules/engine.io/lib/server.js:166:17)
    at Server.handleRequest (/tmp/test/node_modules/engine.io/lib/server.js:220:8)
    at Server.<anonymous> (/tmp/test/node_modules/engine.io/lib/server.js:470:14)
    at Server.<anonymous> (/tmp/test/node_modules/socket.io/lib/index.js:343:16)
    at Server.emit (events.js:315:20)
    at parserOnIncoming (_http_server.js:874:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
```

**Platform:**
 - Device: amd64 desktop machine
 - OS: Linux 5.8.0

**Comment by darrachequesne** [comment]
You are absolutely right, the code provided was not working, sorry for that. Here's the updated answer:

```js
const io = require("socket.io")(httpServer, {
  allowRequest: (req, callback) => {
    callback(null, req.headers.origin === undefined); // cross-origin requests will not be allowed
  }
});
```

This will override the [checkRequest](https://github.com/socketio/socket.io/blob/2.4.1/lib/index.js#L69-L95) method, which has a quite surprising behavior.
