### ISSUE TITLE
getting "TypeError: Cannot read property 'writeHead' of undefined"

### ISSUE THREAD

**Issue by OliverwengFiltered** [socketio/socket.io#3924]
Hi there, it seems we are getting the above error occasionally on certain requests. 
I'm wondering if anyone has any insights around this one ? it appears after we upgrade socket.io version to 4.1.1 
Thanks

here is the stack trace:

```
May 13 15:06:38 prodfiltered app[web] info TypeError: Cannot read property 'writeHead' of undefined
May 13 15:06:38 prodfiltered app[web] info     at sendErrorMessage (/app/node_modules/engine.io/lib/server.js:568:7)
May 13 15:06:38 prodfiltered app[web] info     at Server.handshake (/app/node_modules/engine.io/lib/server.js:291:7)
May 13 15:06:38 prodfiltered app[web] info     at Server.onWebSocket (/app/node_modules/engine.io/lib/server.js:460:12)
May 13 15:06:38 prodfiltered app[web] info     at /app/node_modules/engine.io/lib/server.js:401:14
May 13 15:06:38 prodfiltered app[web] info     at WebSocketServer.completeUpgrade (/app/node_modules/ws/lib/websocket-server.js:330:5)
May 13 15:06:38 prodfiltered app[web] info     at WebSocketServer.handleUpgrade (/app/node_modules/ws/lib/websocket-server.js:246:10)
May 13 15:06:38 prodfiltered app[web] info     at /app/node_modules/engine.io/lib/server.js:400:15
May 13 15:06:38 prodfiltered app[web] info     at Server.verify (/app/node_modules/engine.io/lib/server.js:172:43)
May 13 15:06:38 prodfiltered app[web] info     at Server.handleUpgrade (/app/node_modules/engine.io/lib/server.js:384:10)
May 13 15:06:38 prodfiltered app[web] info     at Server.<anonymous> (/app/node_modules/engine.io/lib/server.js:511:16)
May 13 15:06:38 prodfiltered app[web] info     at Server.emit (events.js:376:20)
May 13 15:06:38 prodfiltered app[web] info     at Server.<anonymous> (/app/node_modules/@pm2/io/build/main/metrics/httpMetrics.js:152:37)
May 13 15:06:38 prodfiltered app[web] info     at onParserExecuteCommon (_http_server.js:699:14)
May 13 15:06:38 prodfiltered app[web] info     at onParserExecute (_http_server.js:612:3)
```

**Comment by darrachequesne** [comment]
I could indeed reproduce the issue, thanks. We will publish a fix as soon as possible.

**Comment by darrachequesne** [comment]
This should be fixed by https://github.com/socketio/engine.io/commit/43606865e5299747cbb31f3ed9baf4567502a879. Could you please check?

**Comment by OliverwengFiltered** [comment]
> This should be fixed by [socketio/engine.io@4360686](https://github.com/socketio/engine.io/commit/43606865e5299747cbb31f3ed9baf4567502a879). Could you please check?

Hi there,

it seems to be working. please release it so our other environment will have it.

Thanks
-Oliver

**Comment by darrachequesne** [comment]
Good news! You should be able to update the `engine.io` package, with either:

- `npm update socket.io`
- or `npm update engine.io --depth 2`

I think we can now close this.
