### ISSUE TITLE
TypeError: Do not know how to serialize a BigInt - JSON encoding too limited

### ISSUE THREAD

**Issue by Domiii** [socketio/socket.io#3982]
**Describe the bug**

Cannot send `BigInt` values. Will result in the following error:

**_TypeError: Do not know how to serialize a BigInt_**
>     at JSON.stringify (<anonymous>)
>     at Encoder.encodeAsString (C:\Users\user\code\myproj\node_modules\socket.io-parser\dist\index.js:69:25)
>     at Encoder.encode (C:\Users\user\code\myproj\node_modules\socket.io-parser\dist\index.js:45:22)
>     at Manager._packet (C:\Users\user\code\myproj\node_modules\socket.io-client\build\manager.js:257:45)
>     at Socket.packet (C:\Users\user\code\myproj\node_modules\socket.io-client\build\socket.js:151:17)
>     at Socket.emit (C:\Users\user\code\myproj\node_modules\socket.io-client\build\socket.js:135:18)
>     at sendNow (C:\Users\user\code\myproj\src\client\Client.js:200:20)
>     at flush (C:\Users\user\code\myproj\src\client\SendQueue.js:45:21)
>     at Timeout._onTimeout (C:\Users\user\code\myproj\src\client\SendQueue.js:36:42)

**To Reproduce**

Socket.IO server version: any (tested with 2.x and also with latest 4.x)

*Server*

```js
import { Server } from "socket.io";

const io = new Server(3000, {});

io.on("connection", (socket) => {
  console.log(`connect ${socket.id}`);

  socket.on("disconnect", () => {
    console.log(`disconnect ${socket.id}`);
  });
});
```

Socket.IO client version: same as server

*Client*

```js
import { io } from "socket.io-client";

const socket = io("ws://localhost:3000/", {});

socket.on("connect", () => {
  console.log(`connect ${socket.id}`);
  socket.emit('test', 1n); // send BigInt here
});

socket.on("disconnect", () => {
  console.log("disconnect");
});
```

**Expected behavior**
`BigInt` (and other es6+ data types) serialization should be supported.

**Related**

This also used to cause #3353 (probably only in older versions, where error reporting was less verbose).

**Solution Suggestion**
The shortcomings of `JSON` have been well established. Good thing is that if `socket.io` moves from `JSON.serialize` to [`serialize-javascript`](https://github.com/yahoo/serialize-javascript) (as a drop-in replacement), `BigInt` and a lot of other new stuff would just work out of the box.

Please consider moving away from `JSON.serialize` to a more modern serialization approach?

**Comment by darrachequesne** [comment]
Hi! I think this is a good use case for a custom parser: https://socket.io/docs/v4/custom-parser/

As for using the `serialize-javascript` package by default, there are two points to take in account:

- the increased size of the bundle
- the browser compatibility

**Comment by Domiii** [comment]
@darrachequesne That does sound like an appealing alternative. I see that one could simply write a `custom-parser` using `serialize-javascript`, and offer that, similar to `socket.io-msgpack-parser` as a separate package.

**Comment by darrachequesne** [comment]
@Domiii that would be awesome indeed! Please ping me if you find the time to do so, we could list it in the page here: https://socket.io/docs/v4/custom-parser/

I think we can now close this.

**Comment by mikiyasET** [comment]
`socket.io-msgpack-parser` throws an _Error: Could not encode_ still having issue while using bigInt 😞

**Comment by darrachequesne** [comment]
@mikiyasET with `socket.io-msgpack-parser` (based on `notepack.io`), you need to attach a `toJSON()` method to `BigInt`:

```js
BigInt.prototype.toJSON = function () {
  return String(this);
};
```

Reference: https://github.com/darrachequesne/notepack/blob/main/README.md#how-to-handle-bigint-values

With `@skgdev/socket.io-msgpack-javascript` (based on `@mgspack/msgpack`), you need to use an extension codec.

Reference: https://github.com/msgpack/msgpack-javascript/blob/main/README.md#handling-bigint-with-extensioncodec

**Comment by Domiii** [comment]
This is how my last version did it:

```js
const CUSTOM_ENCODER = 0;

const extensionCodec = new ExtensionCodec();
extensionCodec.register({
  type: CUSTOM_ENCODER,
  encode: (input) => {
    const t = typeof input;
    switch (t) {
      case 'symbol':
        // convert to string
        return encode(input.toString());
      // case 'function':
      //   warn(`[ENCODE] trying to encode invalid type "${t}":`, input, `(${input.toString()})`);
      //   return encode(input.toString());
      default:
        // don't return anything -> so the default mechanisms can take care of it

        // warn(`[ENCODE] unknown typeof "${t}" (auto-converting to string): ${JSON.stringify(input)}`);
        // return encode(input.toString());
        return undefined;
    }
  },
  decode: (data) => {
    return decode(data);
  },
});
```

**Comment by hskang9** [comment]
I am having the same issue. when will this update to support Bigint? @darrachequesne
