### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected. 

### ISSUE THREAD

**Issue by dymsza** [socketio/socket.io#405]
I have node v0.4.2 and socket.io 0.7.6:  

After these messages the server stops working stably. Error occurs every 2-5h and it very random also it happens only during hight  traffic hours. 

From my observations it appears that there is really a memory leak.

2011-07-21_04:22:41.92346 at Socket. (events.js:101:17)
 2011-07-21_04:22:41.92346 at JSONPPolling.setHandlers (/Chat/js/lib/transport.js:116:15)
 2011-07-21_04:22:41.92347 at JSONPPolling. (/Chat/js/lib/transport.js:71:10)
 2011-07-21_04:22:41.92348 at JSONPPolling. (/Chat/js/lib/transports/http.js:74:39)
 2011-07-21_04:22:41.92349 at JSONPPolling.handleRequest (/Chat/js/lib/transports/http-polling.js:61:41)
 2011-07-21_04:22:41.92350 at JSONPPolling.Transport (/Chat/js/lib/transport.js:32:8)
 2011-07-21_04:22:41.92350 at JSONPPolling.HTTPTransport (/Chat/js/lib/transports/http.js:29:13)
 2011-07-21_04:22:41.92351 at JSONPPolling.HTTPPolling (/Chat/js/lib/transports/http-polling.js:27:17)
 2011-07-21_04:22:41.92352 at new JSONPPolling (/Chat/js/lib/transports/jsonp-polling.js:27:15)
 2011-07-21_04:22:41.92352 at Manager.handleClient (/Chat/js/lib/manager.js:590:19)
 2011-07-21_04:23:02.13106 (node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.

**Comment by iamwave007** [comment]
Does it still leak memory in the newest version?
