### ISSUE TITLE
Error when I use socket.broadcast.emit

### ISSUE THREAD

**Issue by Robotechnic** [socketio/socket.io#4106]
**Describe the bug**
When I use `socket.broadcast.emit` in io.on("connection",callback)
I got this error:
```
TypeError: Cannot read properties of undefined (reading 'apply')
    at Socket.Emitter.emit (pathToMyProject/node_modules/component-emitter/index.js:145:20)
    at Socket.emit (pages/index.js:3311:15)
    at Socket.emitEvent (pages/index.js:3056:20)
    at Socket.onevent (pages/index.js:3043:18)
    at Socket.onpacket (pages/index.js:3007:22)
    at Manager.Emitter.emit pathToMyProject/node_modules/component-emitter/index.js:145:20)
    at Manager.emitReserved (pages/index.js:3324:15)
    at Manager.ondecoded (pages/index.js:2596:14)
    at Decoder.Emitter.emit (pathToMyProject/node_modules/component-emitter/index.js:145:20)
    at Decoder.add (pages/index.js:3636:23)
    at Manager.ondata (pages/index.js:2588:22)
    at Socket.Emitter.emit pathToMyProject/node_modules/component-emitter/index.js:145:20)
    at Socket.onPacket (pages/index.js:550:16)
    at WS.Emitter.emit (pathToMyProject/node_modules/component-emitter/index.js:145:20)
    at WS.onPacket (pages/index.js:951:10)
    at WS.onData (pages/index.js:944:10)
```

Here is my code on server side (with express):
```javascript
const { Server } = require("socket.io")
const io = new Server(server, { //server is the http server instance
	serveClient: false
})
io.on("connection",(socket)=>{
	socket.broadcast.emit("userStatus", {
		userId: someFunctionToGetUserId(),
		status: "connected"
	})
})
```
And on client side (with nuxt js):
```javascript
const io = require("socket.io-client")
var socket = io(process.env.ORIGIN, {
	auth: {
		token : this.$store.state.user.accessToken
	}
})

socket.on("connect",()=>{
	console.log("Connected to the server")
})
```
I am using Arch linux
Node verssion: v16.9.0
Npm version: 7.22.0
Socket-io version: 4.2.0
Socket-io-client version: 4.2.0

**Comment by abhiraj-kale** [comment]
i think you should add the receiving recipient that you are broadcasting to. This can be done by adding 'to' after socket and before broadcast.
`socket.to(**URL of your client**).broadcast.emit("userStatus", {
		userId: someFunctionToGetUserId(),
		status: "connected"
	})`
try this and see if it works
