### ISSUE TITLE
Type error

### ISSUE THREAD

**Issue by qwer-dev** [socketio/socket.io#4181]
TypeError: this.pingIntervalTimer.refresh is not a function
    at Socket.onPacket (/var/www/html/node_modules/engine.io/build/socket.js:107:40)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at WebSocket.onPacket (/var/www/html/node_modules/engine.io/build/transport.js:92:14)
    at WebSocket.onData (/var/www/html/node_modules/engine.io/build/transport.js:101:14)
    at WebSocket.socket.on (/var/www/html/node_modules/engine.io/build/transports/websocket.js:20:19)
    at emitTwo (events.js:126:13)
    at WebSocket.emit (events.js:214:7)
    at Receiver.receiverOnMessage (/var/www/html/node_modules/ws/lib/websocket.js:1022:20)
    at emitTwo (events.js:126:13)

**Comment by darrachequesne** [comment]
Hi! Which version are you using? `Timeout.refresh()` was added in Node.js `v10.2.0`: https://nodejs.org/api/timers.html#timeoutrefresh

**Comment by qwer-dev** [comment]
I'm updated node, its working.

**Comment by big-slime** [comment]
Unfortunately this issue still exists.

### Problem
I am running two electron clients. One acts as a host and client, the other just a client. Around 30 seconds into a successful connection the error appears, causing the server to crash.

### Start Script:
`"start": "tsc && concurrently \"electron .\" \"electron .\"",`

### The Error:
```
VM216 C:\Users\colto\Documents\github\bombastic-man\node_modules\engine.io\build\socket.js:107 Uncaught TypeError: this.pingIntervalTimer.refresh is not a function
    at Socket.onPacket (VM216 C:\Users\colto\Documents\github\bombastic-man\node_modules\engine.io\build\socket.js:107)
    at WebSocket.emit (VM14 node:events:394)
    at WebSocket.onPacket (VM203 C:\Users\colto\Documents\github\bombastic-man\node_modules\engine.io\build\transport.js:92)
    at WebSocket.onData (VM203 C:\Users\colto\Documents\github\bombastic-man\node_modules\engine.io\build\transport.js:101)
    at WebSocket.<anonymous> (VM215 C:\Users\colto\Documents\github\bombastic-man\node_modules\engine.io\build\transports\websocket.js:20)
    at WebSocket.emit (VM14 node:events:394)
    at Receiver.receiverOnMessage (VM219 C:\Users\colto\Documents\github\bombastic-man\node_modules\ws\lib\websocket.js:1022)
    at Receiver.emit (VM14 node:events:394)
    at Receiver.dataMessage (VM234 C:\Users\colto\Documents\github\bombastic-man\node_modules\ws\lib\receiver.js:522)
    at Receiver.getData (VM234 C:\Users\colto\Documents\github\bombastic-man\node_modules\ws\lib\receiver.js:440)
```

### package.json
	"devDependencies": {
		"@types/electron": "^1.6.10",
		"@types/socket.io": "^3.0.2",
		"@types/socket.io-client": "^3.0.0",
		"concurrently": "^6.5.1",
		"electron": "^16.0.5",
		"ts-loader": "^9.2.6",
		"typescript": "^4.5.4"
	},
	"dependencies": {
		"pixi.js": "^6.2.1",
		"socket.io": "^4.4.0",
		"socket.io-client": "^4.4.0"
	}

### Node
```
PS C:\Users\colto\Documents\github\bombastic-man> node --version
v17.3.0
```

### The only function using a timer, server-side (not sure if helpful)
```
function startNetworkUpdate(tickrate: number): void {
	const update = () => {
		console.log("tick");

		io.emit("network-update");

		setTimeout(() => update(), tickrate);
	};

	update();
}
```

**Comment by big-slime** [comment]
Okay, I tried a different approach. It seems to be working correctly if I run the server on it's own process, separate from the main electron process, with this start script:

```"start-with-host": "tsc && concurrently \"node ./dist/server/server.js\" \"electron .\" \"electron .\""```

Not really what I want but I suppose it's a work-around.
