### ISSUE TITLE
Socket SSL Verification Error

### ISSUE THREAD

**Issue by sserpilozdemir** [socketio/socket.io#4389]
Version Compatible:

_python-engineio    4.3.2
_python-socketio    4.6.1__
_Python 3.9.13_

I run a socket with python. After our socket upgrade (socket.io =  4.4.1) socket is not working.

You can see error logs at below:
`
thread created
Starting 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/Users/serpilozdemir/Desktop/socketio_test/./socket_io/position_update_channel_scenario.py", line 32, in run
    asyncio.run(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/serpilozdemir/Desktop/socketio_test/./socket_io/position_update_channel_scenario.py", line 52, in main
    await sio.connect('https://socket.dev.bitronit.com')
  File "/Users/serpilozdemir/Desktop/socketio_test/venv/lib/python3.9/site-packages/socketio/asyncio_client.py", line 116, in connect
    six.raise_from(exceptions.ConnectionError(exc.args[0]), None)
  File "<string>", line 3, in raise_from
socketio.exceptions.ConnectionError: Cannot connect to host socket.dev.bitronit.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')]`

**Comment by darrachequesne** [comment]
Hi! Could you please open an issue in the repository of the Python implementation? Thanks!

Link: https://github.com/miguelgrinberg/python-socketio
