### ISSUE TITLE
Custom developed clients intervene in the Socket.IO service, resulting in service crash

### ISSUE THREAD

**Issue by luhterluo** [socketio/socket.io#4447]
I'm developing a socket The IO client uses an incorrect URL when connecting to the server, but the server crashes。

The part of soket.io URL is：http://hostname/socket.io/?t=9jtKfUz&EIO=4&transport=null&sid=S3FvFdGxFLuUxrrNAAAC

Server report:
TypeError: transports_1.default[transportName] is not a constructor
    at Server.createTransport (/root/r_d/node_socket.io.4/node_modules/engine.io/build/server.js:334:16)
    at Server.onWebSocket (/root/r_d/node_socket.io.4/node_modules/engine.io/build/server.js:438:40)
    at /root/r_d/node_socket.io.4/node_modules/engine.io/build/server.js:398:22
    at WebSocketServer.completeUpgrade (/root/r_d/node_socket.io.4/node_modules/ws/lib/websocket-server.js:408:5)
    at WebSocketServer.handleUpgrade (/root/r_d/node_socket.io.4/node_modules/ws/lib/websocket-server.js:316:10)
    at /root/r_d/node_socket.io.4/node_modules/engine.io/build/server.js:397:21
    at Server.verify (/root/r_d/node_socket.io.4/node_modules/engine.io/build/server.js:81:20)
    at Server.handleUpgrade (/root/r_d/node_socket.io.4/node_modules/engine.io/build/server.js:383:14)
    at Server.<anonymous> (/root/r_d/node_socket.io.4/node_modules/engine.io/build/server.js:495:26)
    at Server.emit (node:events:520:28)

**Comment by darrachequesne** [comment]
Hi! I wasn't able to reproduce the issue:

```js
import { Server } from "socket.io";

const io = new Server(3000);
```

Then

```
curl "http://localhost:3000/socket.io/?t=9jtKfUz&EIO=4&transport=null&sid=S3FvFdGxFLuUxrrNAAACl"
```

returns a HTTP 400 response with the following body: `{"code":0,"message":"Transport unknown"}`

Which version of the `socket.io` package are you using?

**Comment by darrachequesne** [comment]
Closed due to inactivity, please reopen if needed.
