### ISSUE TITLE
[example] Unable to run client app for CRUD app example

### ISSUE THREAD

**Issue by mikebourbeauart** [socketio/socket.io#4875]
**Describe the bug**

Getting this error when I clone and try to run the angular-client via PowerShell for the first time:

```
PS D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client> npm start

> angular-todomvc@0.0.0 start
> ng serve

Compiling @angular/core : es2015 as esm2015
Compiling @angular/common : es2015 as esm2015
Compiling @angular/platform-browser : es2015 as esm2015
Compiling @angular/forms : es2015 as esm2015
Compiling @angular/platform-browser-dynamic : es2015 as esm2015
- Generating browser application bundles...(node:46924) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
\ Generating browser application bundles (phase: building)...node:internal/crypto/hash:68
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\webpack\lib\NormalModule.js:452:10
    at D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\webpack\lib\NormalModule.js:323:13
    at D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\loader-runner\lib\LoaderRunner.js:203:19
    at VirtualFileSystemDecorator.readFile (D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\@ngtools\webpack\src\virtual_file_system_decorator.js:48:13)
    at processResource (D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\loader-runner\lib\LoaderRunner.js:202:11)
    at iteratePitchingLoaders (D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\loader-runner\lib\LoaderRunner.js:158:10)
    at runLoaders (D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\loader-runner\lib\LoaderRunner.js:365:2)
    at NormalModule.doBuild (D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\webpack\lib\NormalModule.js:295:3)
    at NormalModule.build (D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\webpack\lib\NormalModule.js:446:15)
    at Compilation.buildModule (D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\webpack\lib\Compilation.js:739:10)
    at D:\WebProjects\delete_me\socket.io\examples\basic-crud-application\angular-client\node_modules\webpack\lib\Compilation.js:981:14 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.9.0
```

**To Reproduce**

Please fill the following code example:

```
git clone https://github.com/socketio/socket.io.git
cd socket.io/examples/basic-crud-application/
cd angular-client
npm install
npm start
```

**Expected behavior**

App should run

**Platform:**
 - Device: PC
 - OS:  Windows 11

**Additional context**

**Comment by darrachequesne** [comment]
I could indeed reproduce the problem, let me check.

**Comment by darrachequesne** [comment]
I have upgraded the example to Angular v17, this should fix the issue. Have a great day!
