### ISSUE TITLE
Compilation of µWebSockets has failed

### ISSUE THREAD

**Issue by neobie** [socketio/socket.io#5038]
Error: Error: Cannot find module './eiows_v18.19.1'
Require stack:
- node_modules/eiows/dist/eiows.js
- script.js

Compilation of µWebSockets has failed.Please install a supported C++17 compiler, git and/or update node and reinstall the module 'eiows'.
    at node_modules/eiows/dist/eiows.js:27:15
    at Object.<anonymous> (node_modules/eiows/dist/eiows.js:30:3)
    
    have been trying with eiows v3 to v7, all failed. 
    g++ is available.

**Comment by darrachequesne** [comment]
Hi! Which version of `eiows` are you using?

Source code: https://github.com/mmdevries/eiows

**Comment by neobie** [comment]
> Hi! Which version of `eiows` are you using?
> 
> Source code: https://github.com/mmdevries/eiows

should be this one. is there any other variance ?

**Comment by Avasam** [comment]
@neobie run `npm list eiows` to get your eiows version

**Comment by darrachequesne** [comment]
I think this can be closed now. Please reopen if needed.
